### ISSUE TITLE
Make actions returned FSA compliant

### ISSUE THREAD

**Issue by pburtchaell** [pburtchaell/redux-promise-middleware#1]
I think it would be best to make sure the actions returned and accepted by the middleware follow a standard. Right now, the actions dispatched from the promise are FSA compliant, but the `types` array used in the action creators is not a part of the standard. Need to figure out how to handle that. 

One thought is to just have one `type` instead of an array and just append `_FULFILLED` and `_REJECTED` to that type.

**Comment by davidwatkins73** [comment]
Auto post fixing works for me.  At the moment I'm using a small generator function to produce the 3 variant action types, so this proposal would remove the need for that.

**Comment by pburtchaell** [comment]
Great! Yeah, I think this is the way to go. I'm away on vacation until August 10, but I plan to work on this improvement after then. :smile:

**Comment by jarsbe** [comment]
It would might be nice to specify the suffix, and another thing to think about is sometimes it's a prefix:

`BEGIN_STUFF`, `SUCCESS_STUFF`, `ERROR_STUFF`

```
const config = {
   fulfilled: '_SUCCESS',
   rejected: '_ERROR'
}

promiseMiddleware(config)
```

Having said all that having the decision made for you on async actions is rather nice.

**Comment by deoxxa** [comment]
This might need to happen sooner rather than later, with https://github.com/rackt/redux/releases/tag/v3.0.0 being a thing.

**Comment by pburtchaell** [comment]
It will always create actions with a `type` other than undefined so this is safe.

**Comment by deoxxa** [comment]
But it'll be hard to get those actions into the middleware unless they have a type themselves, won't it?

**Comment by pburtchaell** [comment]
Yes, that is correct—not sure what I was thinking before. I can change it to `type`. 

Do you have any opinions on sending an array v. not sending one? I am not opposed to my original idea of having one type and appending `_FULFILLED` and `_REJECTED` to that type. 

The only problem is some people like to have a generic fulfilled/rejected type, e.g., `REQUEST_PENDING`, `MY_ASYNC_ACTION, and `REQUEST_REJECTED`. Personally, I don't do this, but a few people on Slack who use this middleware brought that to my attention.

**Comment by deoxxa** [comment]
Appending the `_FULFILLED` and `_REJECTED` suffixes seems plenty reasonable.

A good middle ground might be an override mechanism, as an escape hatch if there's a particular reason why someone would want their own action names. I would probably end up using this kind of system personally, as I like to keep action names in a separate file so I can see them all in one place.

e.g.

```js
import {
  FETCH_WIDGETS,
  FETCH_WIDGETS_GETREADY,
  FETCH_WIDGETS_ALLDONE,
  FETCH_WIDGETS_OHDEAR,
} from './constants';

dispatch({
  type: FETCH_WIDGETS,
  promiseTypes: {
    pending: FETCH_WIDGETS_GETREADY,
    fulfilled: FETCH_WIDGETS_ALLDONE,
    rejected: FETCH_WIDGETS_OHDEAR,
  },
  // ...
})
```

**Comment by kainoa21** [comment]
+1 for supporting an override at a minimum

**Comment by tomatau** [comment]
Have been using something similar!

Made a PR here: https://github.com/pburtchaell/redux-promise-middleware/pull/10

**Comment by pburtchaell** [comment]
Nice! I will check it out this weekend and try to get it merged. Just to let you all know, I am also working on some changes to the middleware on the dev branch.

**Comment by pburtchaell** [comment]
Update: PR #10 looks great; thanks @tomatau! With a rebase and one minor change, this should be resolved.

**Comment by tomatau** [comment]
@pburtchaell Done :)

**Comment by pburtchaell** [comment]
Ok. So as of version 2.0.0 everything is FSA compliant.
