### ISSUE TITLE
Rejected promises crash Redux Devtools

### ISSUE THREAD

**Issue by Kovensky** [pburtchaell/redux-promise-middleware#104]
Redux Devtools records the dispatched actions using `JSON.stringify`, and there is an `action.payload.action` loop (which makes JSON throw) when dispatching the `REJECTED` side of the promise.

**Comment by pburtchaell** [comment]
@Kovensky Which version are you using? There is a known circular reference issue (see #101) in > 3.3.1.

**Comment by Kovensky** [comment]
Yeah, seems this is the same issue as described in #101.
