### ISSUE TITLE
Returning promise from middleware

### ISSUE THREAD

**Issue by steida** [pburtchaell/redux-promise-middleware#109]
Congrats for version 4 release. Sorry, I was rude in previous issues, just burnout.
I think I can formulate a problem I have with returning promises better now.

From my point of view, sooner or later any app will need global error handling.
If returning promises is allowed, it's easy to write:

```js
// in component onSaveClick()
try {
  await this.props.isAllowed();
  await this.props.save();
} catch (e) {
  ...  
}
this.showSaveState();
```

Then the async workflow leaks from actionCreator to component.
Then it's hard to handle errors globally.
Maybe it's over of the scope of this library, maybe we need another level of abstraction like Saga. I'm not sure.

**Comment by tomatau** [comment]
What's the problem with using a middleware to handling errors? All the errors from this middleware will be dispatched -- this would actually be the recommended place to handle errors in a more global sense. You can still window.onunhandledrejection for the rest.

**Comment by steida** [comment]
I am doing that in the github.com/este/este. The problem is, when the middleware returns a promise, developer tends to use it and "async flow" leaks from action creator to the component. I also had some problem with bluebird warnings about "possible unhandled rejection" but I can't remember the exact case.

**Comment by pburtchaell** [comment]
It makes sense to return a promise. It enables one to create async flows using `then` and other promise methods like `Promise.all` and `Promise.race`; this is what the middleware is designed to do. Changing the middleware to not return a promise would remove the ease of this functionality. 

Besides, there are ways to implement both global error handling and async flows. See the complex example for this middleware; there is an action creator with "local" error handling and one with global error handling (middleware).

**Comment by pburtchaell** [comment]
I should say, I appreciate your feedback on the middleware. I understand you used the middleware in in [Este](github.com/este/este) and you're encountering problems. I think the risk, though, is optimizing the middleware for the specific problems encountered in Este. I'm happy to work through these problems and I think they can be solved without changing the middleware design.
