### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0):  Error at handleReject

### ISSUE THREAD

**Issue by indie314** [pburtchaell/redux-promise-middleware#116]
Hello,

I have an android app and a backend written in node.js.

For the app I use redux + [redux-promise-middleware](https://github.com/pburtchaell/redux-promise-middleware).

I have the following action:

```
export const createUser = (data) => ({
  type: types.CREATE_USER,
  payload: new Promise( (resolve, reject) => API.createUser(data, resolve, reject) )
})
```

And the API where I reject the promise if json has an error message:

```
export const createUser = (data, resolve, reject) =>
  API.post('user', data)
    .then( res => res.json() )
    .then( json => json.error ? reject(json) : resolve(json) )
    .catch( e => reject(e) )
```

So after I dispatch the createUser action I recive the following YellowBox warning:

> Possible Unhandled Promise Rejection (id: 0):  Error at handleReject

The error is not showing if in .then I do like this:

```
 .then( json => resolve(json) )
````

---

```
› react-native -v
react-native-cli: 0.2.0
react-native: 0.31.0
```

Can someone explain why this is happening?

**Comment by pburtchaell** [comment]
Given this action creator:
```js
// ❎
export const createUser = (data) => ({
  type: types.CREATE_USER,
  payload: new Promise( (resolve, reject) => API.createUser(data, resolve, reject) )
})
```
You shouldn't construct a new promise in the action creator and pass the handlers down as callbacks. Callbacks and promises are two different solutions for async functionality. Don't mix them like this; that's an anti-pattern. Instead `API.createUser`, should **return** a promise object.
```js
// ✅
export const createUser = (data) => ({
  type: types.CREATE_USER,
  payload: API.createUser(data)
})
```
Right now, your code is super verbose, which I expect is part of the problem. I would suggest reading through some of the known [promise anti-patterns](http://bluebirdjs.com/docs/anti-patterns.html). I also need to know the version number you are using.
