### ISSUE TITLE
Send value to reducer

### ISSUE THREAD

**Issue by justintv90** [pburtchaell/redux-promise-middleware#117]
Hi

This is an amazing middleware but can you please let me know how to send/pass a value from action to reducer

I used like that
`export function projectDelete(id) {
    return ({
        type: constants.PROJECT_DELETE,
        value: id,
        payload: axios.delete(`${API_URL}/project/delete?id=${id}`)
    })
}`

But in reducer when I want to receive id value by using `let id = action.value`, the output is undefined. How to do that, please help me

**Comment by pburtchaell** [comment]
The way to get the value from action creator to reducer is to resolve/reject the promise with a value/reason. The value/reason will be the payload of the dispatched fulfilled action. Please refer to [the documentation](https://github.com/pburtchaell/redux-promise-middleware/tree/master/docs) and [examples](https://github.com/pburtchaell/redux-promise-middleware/tree/master/examples) for more information.
