### ISSUE TITLE
Recursion in handleReject when Promise reason is an `instanceof Error`

### ISSUE THREAD

**Issue by NaitoKenzo** [pburtchaell/redux-promise-middleware#119]
## Version

3.3.2

## Test Case

I put together an API middleware with fetch that dispatches an action with a payload that corresponds to:

`new Error({error: 'No token found'})`

The problem I'm facing is that the payload creates a recursion which I believe comes from the handleReject function returned in your main file.

```javascript
var handleReject = function handleReject() {
  var reason = arguments.length <= 0 || arguments[0] === undefined ? null : arguments[0];
  var rejectedAction = getAction(reason, true);
  dispatch(rejectedAction);
  

  // If reason is an instanceof Error, then error.reason becomes itself I think?
  var error = reason instanceof Error ? reason : new Error();

  error.reason = reason;
  error.action = rejectedAction;
  throw error;
 };
```

The reason I want to dispatch a payload with a rejected promise is because I would like to catch errors at a global level. So I dispatch errors when the `fetch`ed response contains errors.

## Steps to reproduce

Dispatching this does the job on my end:

```javascript
{
    type: actionType,
    meta: 'GLOBAL_ERROR',
    payload: Promise.reject(err),
};
```
## Expected Behavior
I'm using the error middleware you suggested, so the ideal behavior would be a warning triggered by:

```javascript
result.catch(error => {

        console.warn(`${action.type} caught at middleware with reason: ${JSON.stringify(error.message)}.`);
        return error;
      });
```

The problem is that error.message is undefined because of the loop.

## Actual Behavior
The lopp triggers an error:
Uncaught TypeError: Converting circular structure to JSON

**Comment by pburtchaell** [comment]
If you switch to [4.0.0](https://github.com/pburtchaell/redux-promise-middleware/releases/tag/4.0.0), this issue should be resolved. Did you get a depreciation warning when using 3.3.2?

**Comment by NaitoKenzo** [comment]
Indeed! Sorry, I should have looked more closely at the docs.
