### ISSUE TITLE
On error returning _ERROR_LOADING  or _REJECTED_PENDING as action type.

### ISSUE THREAD

**Issue by hafeez1042** [pburtchaell/redux-promise-middleware#122]
Hi,
i can't handle error response from API request, if the response was 404 or 500, i am getting _ERROR_LOADING instead of _ERROR. can you please suggest a solution.

**Comment by pburtchaell** [comment]
Issues should primarily be for bug reports, feature requests and other issues directly related to the middleware. If you are going to ask for help, that's fine, but you should make sure that your issues contain specific information and code examples.

This is not related to the middleware, but rather how you are handling your errors. The middleware dispatches rejected issues for rejected promises. If you are getting `_ERROR_LOADING`, then that means you are not rejecting the promise when the response is 404 or 500.
