### ISSUE TITLE
Support promise.prototype.finally

### ISSUE THREAD

**Issue by pburtchaell** [pburtchaell/redux-promise-middleware#124]
Like #77, the purpose of this issue track new promise feature and one that could be relevant to this library. The [`finally` prototype method](https://github.com/tc39/proposal-promise-finally) has advanced to stage 2 at TC39. 

``` js
promise.then(fn, fn).finally(fn)
```

If we were to support this, I imagine the middleware will simply dispatch a third action type, e.g., `FOO_ACTION_FINALLY`. This action would describe a change in state that is the same regardless of the settled promise state.

Reminder: stage 2 is a feature draft. This is speculative.

**Comment by pburtchaell** [comment]
I think it's probably best if we leave this alone for now. We can reopen if there is a need for it.

**Comment by redexp** [comment]
+1 for it, here code how I want to use it
```javascript
handleActions({
	[loadEvents]: {
		[LOADING]: function (state) {
			return {...state, loading: true};
		},
		[SUCCESS]: function (state, {payload: {items, total}}) {
			return {...state, items, total};
		},
		[FINALLY]: function (state) {
			return {...state, loading: false};
		},
	}
}, {
	loading: false,
	items: [],
	total: 0
})
```
instead of
```javascript
handleActions({
	[loadEvents]: {
		[LOADING]: function (state) {
			return {...state, loading: true};
		},
		[SUCCESS]: function (state, {payload: {items, total}}) {
			return {...state, items, total, loading: false};
		},
		[ERROR]: function (state) {
			return {...state, loading: false};
		},
	}
}, {
	loading: false,
	items: [],
	total: 0
})
```

**Comment by pburtchaell** [comment]
@redexp, can you explain further what benefit or advantage you'd get from a `FINALLY` action? Or, could you explain how you'd use it in your application?

In this example, are you using the final action instead of the `ERROR` action? It wouldn't make sense to use `FINALLY` instead of `ERROR` because the finally method is invoked when a promise is settled (either fulfilled or rejected).

**Comment by tribou** [comment]
I came across a repo that used `Promise.prototype.finally()` to reset loading indicator states. It's not a big deal since you can also add the code to reset it in both the SUCCESS and ERROR, but it is nice having it in a single case:

e.g.

```js
handleActions({
	[loadEvents]: {
		[LOADING]: function (state) {
			return {...state, loading: true };
		},
		[SUCCESS]: function (state, {payload: {items, total}}) {
			return {...state, error: '', items, total};
		},
		[ERROR]: function (state, { payload : { message }) {
			return {...state, error: message };
		},
		[FINALLY]: function (state) {
			return {...state, loading: false};
		},
	}
}, {
	loading: false,
	items: [],
	total: 0,
        error: ''
})
```
