### ISSUE TITLE
Change Meta for Fulfilled action

### ISSUE THREAD

**Issue by tomatau** [pburtchaell/redux-promise-middleware#13]
I'm happy to make a PR for this but wanted to run it past everyone else in an issue first.

My use case: I'm using async actionCreators to make API calls that request updates to persisted data, once fulfilled, I'd like the success action to be distributed over a web-socket using https://github.com/rstuven/redux-via-socket.io. This is achieved by supplying meta options in the action you would like to send to the server, for example `meta: { broadcast: true }`. I hope to only broadcast the FULFILLED promiseTypeSuffix as other clients don't give a rats fiddle about the pending and error :)

Here's an example of the API:
```es6
const addItem = async (body) => {
  const {item} = await itemGateway.addItem(body)
  return {
    payload: { item },
    meta: { broadcast: true }
  }
}

export const addITem = (item) => ({
  type: ADD_ITEM,
  payload: {
    data: { item },
    promise: addItem(item)
  }
})
```

Here resolving the complete action (without type) to the promise.

I have this already working locally on a project using my own fork... also I'd like to make it work by either resolve a `{ payload, meta }`  or just resolving the payload with no change the the meta data (to keep backwards compatibility and remove boilerplate).

**Comment by pburtchaell** [comment]
I'm not super familiar with what you would be trying to do so let me see if I understand this problem you are trying to solve before we go forward with this.

1. You fire an action to add an item.
2. That action makes a network request (which I will call the "initial request") and that request is handled by the promise middleware.
3. Once that request is successfully handled, a second action is dispatched. This action includes the response from the initial request and a `meta.broadcast` property. 
4. The promise middleware sees this `meta.broadcast` property and dispatches a `FULFILLED` action type.

Could this be something handled in a second middleware? Maybe I am not understanding what you are doing. :confounded:

**Comment by tomatau** [comment]
Apologies for being a little bit messy with my initial description:

1. First action with promise payload, and no meta, promise middleware finds this and dispatches {action}_PENDING
2. When the promise resolves, promise middleware currently dispatches {action}_FULFILLED using the same meta as the original action. This is what I want to be able to customise. Making it possible for my promise object to resolve additional meta information.

I have another middleware that makes use of a `{meta: { broadcast: true } }`... I would like to manually set this meta object for specifically the `{action}_FULFILLED` type, without affecting the `{action}_PENDING or REJECTED`.

**Comment by pburtchaell** [comment]
I see. I think that makes sense. Feel free to make a PR and we can work from there!

**Comment by tomatau** [comment]
Quickly threw this together.. although it's Sunday night and coffee can only prevent so many bugs :D (I haven't properly tested this... we should add tests)

https://github.com/pburtchaell/redux-promise-middleware/pull/15

**Comment by pburtchaell** [comment]
Yeah, I think you should check if the resolved object is a FSA—which would require a `payload` prop, but not a `meta` prop.

This looks good. I can merge it in after you make that change.

**Comment by tomatau** [comment]
Looking at the source code of FSA it seems they don't require any keys other than `type`

https://github.com/acdlite/flux-standard-action/blob/master/src/index.js#L14

I think either meta or payload would make most sense. Will make the change now
