### ISSUE TITLE
Provide dist files for old versions

### ISSUE THREAD

**Issue by pvnr0082t** [pburtchaell/redux-promise-middleware#131]
For help, use this template:

## Version Number
Versions from v0.0.0-v3.3.1 published on NPM

Hi @pburtchaell , 
I'm a member of [cdnjs](http://github.com/cdnjs/cdnjs), we want to host this library.
I found that there are no `ReduxPromiseMiddleware.js` and `ReduxPromiseMiddleware.min.js` before v3.3.2, but I think that are the files need to be hosted. Could you please provide these files from v0.0.0-v3.3.1? 
BTW, I'd like to confirm that if `index.js` and `isPromise.js` also need to be hosted or not?
Thank you.

https://github.com/cdnjs/cdnjs/issues/9544

**Comment by pburtchaell** [comment]
Hi! Exciting! I'm happy to help you setup everything to host the library. 😄 

> I found that there are no ReduxPromiseMiddleware.js and ReduxPromiseMiddleware.min.js before v3.3.2, but I think that are the files need to be hosted. Could you please provide these files from v0.0.0-v3.3.1?

What is the best way for me to provide these files? 

> I'd like to confirm that if index.js and isPromise.js also need to be hosted or not?

No, `index.js` and `isPromise.js` are the source files.

**Comment by pvnr0082t** [comment]
>What is the best way for me to provide these files?

@pburtchaell You can provide these files by compressing them to `.zip` or `.tar` and we can download it. If you have a better way for you to share files, you can use that. Thank you.

**Comment by pburtchaell** [comment]
Perfect. I won't be available this week to resolve this, but I should have some time in the following week.

**Comment by pburtchaell** [comment]
Hi @pvnr0082t, I'm looking more into this issue today. 

From your original description:

> There are no `ReduxPromiseMiddleware.js` and `ReduxPromiseMiddleware.min.js` before v3.3.2

These are UMD build files ([see release notes](https://github.com/pburtchaell/redux-promise-middleware/releases/tag/3.3.2)). Does cdnjs need UMD files? 

>  I'd like to confirm that if `index.js` and `isPromise.js`  also need to be hosted or not?

In [the previous comment on 12/11](https://github.com/pburtchaell/redux-promise-middleware/issues/131#issuecomment-266343913), I said these were "source" files, but that wasn't very clear. 

Actually, these files are published to npm and `index.js` is referenced in package.json as the main script. I assume these are the files you need, then?

**Comment by pvnr0082t** [comment]
@pburtchaell 
>These are UMD build files (see release notes). Does cdnjs need UMD files?

Yes, UMD files can be hosted in cdnjs. Actually, we want to host the files which for distributed purpose. The files should work in browser, so I think `ReduxPromiseMiddleware.js` and `ReduxPromiseMiddleware.min.js` are the files we need.

**Comment by pburtchaell** [comment]
Okay. For versions `<3.3.2`, it is fairly easy to checkout each release and run the existing build script; [I did that today](https://www.dropbox.com/sh/g5p2dj99cwx46ni/AAAZ3t7jFJ0fpxaLY83EH8Yca?dl=0). However, the existing build script generates only the `index.js` and `isPromise.js` files, and as you said, these aren't the files you need.

Getting the UMD files for versions `<3.3.2` will be a slow process. I would need to checkout each release, add the UMD build tools (in this case, WebPack), install dependencies (some of the older releases use Babel v5) and upload the files to you. The slowest step in this process would be adding the UMD build tools. It certainly isn't impossible though.

That being said, before I start any work on this, is it required to have all versions published on cdnjs, or can we start from v3.3.2?

**Comment by pvnr0082t** [comment]
I'd like to have all versions published on cdnjs, but if you don't suggest to use versions before v3.3.2, we can ignore them and maybe just start from v3.3.2. How do you think?

**Comment by pburtchaell** [comment]
I think that would work, but let me think about it. Since we have 2.x and 1.x listed on the README as previous versions, I think we could at least include the initial and stable releases of each. What do you think of that?

**Comment by tomatau** [comment]
> I'd like to have all versions published on cdnjs, but if you don't suggest to use versions before v3.3.2, we can ignore them and maybe just start from v3.3.2. How do you think?

I'm still supporting and working with 2.4.0 every day. It has been stable for quite some time now.

**Comment by pburtchaell** [comment]
Yeah, so I'm thinking we should at least include v2.x, @tomatau.

**Comment by pvnr0082t** [comment]
@pburtchaell I think it's okay if you want stable versions before v3.3.2 to be hosted only.

**Comment by tomatau** [comment]
I install 2.4 through npm, not a CDN. If it was available on the latest redux-promise-middleware through a direct ref to `redux-promise-middleware/dist/v2.4.0.js` or whatever then that would be great for me -- can finally get rid of that suggestion to update.

**Comment by pburtchaell** [comment]
@pvnr0082t My thoughts are to host the following versions (liked to Dropbox folders with build):

- [2.4.0](https://www.dropbox.com/sh/c23sms4i2vbvp8q/AABZMEMAHIQlLTitp9ZTKjtWa?dl=0) (latest stable version of 2.x)
- [3.1.0](https://www.dropbox.com/sh/zzdqc5zn7ud4es3/AAAdiotVCJSfajb2b6vdCFPFa?dl=0)
- [3.3.0](https://www.dropbox.com/sh/bupeke6vn7s5evc/AAACGc9GqFPVdaN4ZAEbT86Ca?dl=0)
- [3.3.1](https://www.dropbox.com/sh/gny3hhhlrw9pz71/AAAeD8V9v-JImuLzcpydVtKba?dl=0)

I think we can skip 1.x of the middleware because it supported older versions of Redux 2.x and 3.x, which are not widely in use.

**Comment by pvnr0082t** [comment]
@pburtchaell Okay, thanks for your big help. :facepunch:

**Comment by pburtchaell** [comment]
I am happy to help! Let me know when it is published. 😄 

Also, just to confirm, the latest versions—starting with `4.0.0`— will also be hosted too, correct?

**Comment by pvnr0082t** [comment]
Yes, there is a auto-updater to update library in cdnjs automatically when the latest version published.
