### ISSUE TITLE
Testing strategies

### ISSUE THREAD

**Issue by andrewmclagan** [pburtchaell/redux-promise-middleware#132]
Are there any standard testing strategies for this library?

* testing reducers

* testing async action creators

I would be interested in writing a docs PR if people could outline their testing strategies vs our own.

**Comment by pburtchaell** [comment]
I don't have any standards to suggest right off the bat. Generally, I've written tests using [the tests for the middleware](https://github.com/pburtchaell/redux-promise-middleware/tree/master/test) as a model. 

Do you have any suggestions, @andrewmclagan? I'd also be curious on your comments here, @tomatau!

**Comment by andrewmclagan** [comment]
Firstly we are only just migrating to `redux-promise-middleware` from our custom thunk middleware.

**REDUCERS:**

I would not be testing the middleware as it has tests in the library. But rather testing how the reducer responds to `*_REQUEST`, `*_SUCCESS`, `*_FAILURE` actions. My only concern is keeping our test codebase DRY, as we don't actually have action creators for those three actions this becomes difficult.

**ACTION CREATORS**

Easy. Simply do a deep equality test on the output of the action creator:

````javascript
// TEST FILE: actions.spec.js 
import * as AppActions from 'store/app/actions';

test('fetchAppData creates correct async action', () => {
  expect(AppActions.fetchAppData()).toEqual({
    type: AppActions.FETCH_APP_DATA,
    payload: Api.initialize(params),
  });
});

````

````javascript
// ACTIONS FILE: actions.js
import { createActionType, createAction } from 'store/utils';
import Api from 'library/api';

/*
|--------------------------------------------------------------------------
| Action Types
|--------------------------------------------------------------------------
*/

export const FETCH_APP_DATA = createActionType('APP/FETCH_DATA');

/*
|--------------------------------------------------------------------------
| Async Actions
|--------------------------------------------------------------------------
*/

export function fetchAppData() => createAction(FETCH_APP_DATA, {
  payload: Api.initialize(),
});
````

**Comment by andrewmclagan** [comment]
The following is how we currently test reduceers, my concern is manually reacting the three actions:

`*_REQUEST, *_SUCCESS, *_FAILURE`

````javascript
import Immutable from 'immutable';
import * as AppActions from 'store/app/actions';
import appReducer, { initialState } from 'store/app';
import { response, error } from 'store/app/__tests__/_fixtures';

test('should return correct initial state', () => {
  const expected = Immutable.fromJS({
    fetching: false,
    error: false,
    taxonomies: {},
    enumerables: {},
    creditPacks: [],
  });
  expect(Immutable.is(appReducer(undefined, {}), expected)).toBe(true);
});

test('should handle FETCH_APP_DATA_REQUEST action correctly', () => {
  const action = {
    type: `${AppActions.FETCH_APP_DATA}_REQUEST`,
    payload: response,
  };
  const expected = initialState
    .set('fetching', true)
    .set('error', false);
  const actual = appReducer(initialState, action);
  expect(Immutable.is(expected, actual)).toBe(true);
});

test('should handle FETCH_APP_DATA_SUCCESS action correctly', () => {
  const action = {
    type: `${AppActions.FETCH_APP_DATA}_SUCCESS`,
    payload: response,
  };
  const expected = initialState
    .set('fetching', false)
    .set('error', false)
    .set('taxonomies', response.data.taxonomies)
    .set('enumerables', response.data.enumerables)
    .set('creditPacks', response.data.creditPacks);
  const actual = appReducer(initialState, action);
  expect(Immutable.is(expected, actual)).toBe(true);
});

test('should handle appData.failure action correctly', () => {
  const action = {
    type: `${AppActions.FETCH_APP_DATA}_FAILURE`,
    payload: response,
  };
  const expected = initialState
    .set('fetching', false)
    .set('error', Immutable.fromJS(error));
  const actual = appReducer(initialState, action);
  expect(Immutable.is(expected, actual)).toBe(true);
});


````

**Comment by andrewmclagan** [comment]
I guess that verbosity is the price we pay for the reduction in boilerplate?

**Comment by siemiatj** [comment]
Yeah I'd love to see examples of tests like in redux documentation : http://redux.js.org/docs/recipes/WritingTests.html#async-action-creators

**Comment by tomatau** [comment]
I test in a similar manner to what you've posted and find the `*_REQUEST, *_SUCCESS, *_FAILURE` explicitness useful in my tests. It's also more clear for newcomers joining my team who are still learning. Aiming for DRY here isn't such a big win?.. If you find the same pattern between multiple reducers then perhaps make an abstraction and test that once -- then test that the reducers use that abstraction instead of repeating the tests.

If the repeated template strings/concatenation of the promiseTypeSuffixes is a problem, perhaps make 3 functions that do that for you and reuse those functions instead. This can also be shared with your reducer functions themselves if you use the same suffixes throughout your project.

```js
const requestType = (type) => `${type}_REQUEST`

test('should handle FETCH_COLLECTION_REQUEST action correctly', () => {
  const action = {
    type: requestType(ActionTypes.FETCH_COLLECTION),
  };
  const actual = invoiceReducer(initialState, action);
  expect(Immutable.is(actual, expectedRequestState)).toBe(true);
});
```

**Comment by tomatau** [comment]
Here's a test file from my colleague and I think it works just fine!

```js
import accountReducers from './accountCheck.reducers'
import { ACCOUNT_CHECK } from './accountCheck.actions'

describe('Account Check Reducers', function() {
  const initialState = {
    isPending: false,
    error: false,
    data: {},
  }
  const irrelevantAction = { type: 'IRRELEVANT_ACTION' }

  it(`returns the initialState when no state`, () => {
    expect(accountReducers(undefined, irrelevantAction)).to.eql(initialState)
  })

  describe(`ACCOUNT_CHECK`, () => {
    beforeEach(() => {
      this.previousState = {
        some: 'test random state',
      }
    })

    describe(`REQUEST`, () => {
      const accountRequestAction = {
        type: `${ACCOUNT_CHECK}_REQUEST`,
      }

      it(`sets initialState with isPending:true`, () => {
        const newState = accountReducers(this.previousState, accountRequestAction)
        expect(newState).to.eql({
          ...initialState,
          isPending: true,
        })
      })
    })

    describe(`ERROR`, () => {
      const accountErrorAction = {
        type: `${ACCOUNT_CHECK}_ERROR`,
        error: true,
        payload: new Error('some error'),
      }

      it(`sets initialState with error from action`, () => {
        const newState = accountReducers(this.previousState, accountErrorAction)
        expect(newState).to.eql({
          ...initialState,
          error: accountErrorAction.payload,
        })
      })
    })

    describe(`RECEIVE`, () => {
      const accountRecieveAction = {
        type: `${ACCOUNT_CHECK}_RECEIVE`,
        payload: {
          test: 'test payload',
        },
      }

      it(`sets initialState with data as action's payload`, () => {
        const newState = accountReducers(this.previousState, accountRecieveAction)
        expect(newState).to.eql({
          ...initialState,
          data: accountRecieveAction.payload,
        })
      })
    })
  })
})
```

**Comment by pburtchaell** [comment]
> This issue feels more related to writing unit tests in general and writing tests for reducers in general. It's not really specific to this middleware.

I agree with @tomatau that this isn't directly related to the library, but to general testing of reducers   and async action creators. That being said, it would be useful to have more extensive documentation—as well as a complete example—on this subject. I think testing often gets excluded when community docs are written. 

Perhaps we could add a guide to [the middleware docs](https://github.com/pburtchaell/redux-promise-middleware/tree/master/docs/guides)? 

Would you be interested in taking an initial stab at that, @andrewmclagan?

**Comment by siemiatj** [comment]
Well I was actually thinking about how to write tests for action creators that perform some XHR requests. I'm struggling to get this working after 2 days now and reading through a lot of source code (including packages and node itself). So I have a simple action creator like this one : 

`
const createProject = (subCategoryId, title) => (dispatch) => (
  dispatch({
    type: CREATE,
    payload: axios.post('/api/v1/projects/', {
      sub_category: subCategoryId,
      title,
    })
  })
);
`

And now I'm trying to write a test case for it. So I used the standard approach here : 

`
it('Creates a project if one does not exists yet', (done) => {
  nock('http://django:8000')
    .post('/api/v1/projects')
    .reply(200, { body: { data: { ...projectData } } });

  const expectedActions = [
    {
      type: commonImports.CREATE_PENDING,
      sub_category: projectData.sub_category,
      title: projectData.title,
    }, {
      type: commonImports.CREATE_FULFILLED,
      payload: { ...projectData },
    }
  ];
  const store = mockStore({
    pap: { project: { data: null } },
  });

  store.dispatch(createProject(projectData.sub_category, projectData.title));
    .then((res) => {
      expect(store.getActions()).toEqual(expectedActions);
    })
    .then(done)
    .catch(done);
});
`

but I'm getting `(node:48825) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'protocol' of undefined`

**Comment by tomatau** [comment]
@siemiatj - I'd suggest stubbing your dependency (axios) rather than stubbing the endpoint through nock. It will make your test run quicker and you won't actually need to open any requests.

It will also solve your problem as axios when run in node context (not the browser) uses http which has different behaviour to XHR - it requires a full url with protocol.

I really don't understand how nock has become so popular in this situation tbh, sinon.stub is even less verbose! Nock really just doesn't make sense as a "unit" test library - it's for "functional", acceptance or some people's take on "integration" tests.

**Comment by tomatau** [comment]
Here's a file and it's tests from one of my colleagues

```js
import * as Thing from './services/Thing';
import config from 'config/app.config';

const actions = {
  GET_THINGS: 'GET_THINGS',

  getThings: (token) => ({
    type: actions.GET_THINGS,
    payload: {
      promise: Thing.getThings(token)
    }
  })
};

export default actions;
```

And the tests (sorry if they're broken I've had to delete some stuff in githubs comment editor)

```js
import { expect } from 'chai';
import actions from './';
import configureStore from 'redux-mock-store';
import thunk from 'redux-thunk';
import promiseMiddleware from 'app/store/promise-middleware';
import * as Thing from './services/Thing';
import sinon from 'sinon';
import config from 'config/app.config';

describe('Thing Actions', () => {
  let store;
  beforeEach(() => {
    sinon.stub(Thing, 'getServiceChecks');
    const mockStore = configureStore([thunk, promiseMiddleware()]);
    store = mockStore({});
  });

  afterEach(() => {
    Thing.getServiceChecks.restore();
  });

  describe('Action types are types', () => {
    expect(actions.GET_THINGS).to.eql('GET_THINGS');
  });

  describe('serviceChecks()', () => {
    context('Given Thing.getThings() resolves', () => {
      const resolvedObject = { value: 'whatever' };
      beforeEach(() => {
        Thing.getThings.returns(Promise.resolve(resolvedObject));
      });

      it('should return a GET_THINGS action', () => {
        expect(actions.getThings("1234557")).to.have.property(
          'type', actions.GET_THINGS
        );
      });

      it('should resolve the resolvedObject from Things', () => {
        expect(
          actions.getThings().payload.promise
        ).to.become(resolvedObject);
      });

      it('dispatches GET_THINGS_PENDING and GET_THINGS_FULFILLED actions', () => {
        const testData = { test: '1234' };
        const expectedActions = [{
          type: `${actions.GET_THINGS}_PENDING`
        }, {
          type: `${actions.GET_THINGS}_FULFILLED`,
          payload: testData
        }];

        Thing.getThings.returns(Promise.resolve(testData));
        return store.dispatch(actions.getThings('1234'))
          .then(() => expect(store.getActions()).to.eql(expectedActions));
      });
    });

    context('Given Thing.getThings() rejects', () => {
      const rejectedObject = new Error('404');
      beforeEach(() => {
        Thing.getThings.returns(Promise.reject(rejectedObject));
      });

      it('should reject the rejectedObject', () => {
        expect(actions.getThings('12345').payload.promise).to.be.rejectedWith(rejectedObject);
      });

      it('dispatches PENDING and REJECTED actions', () => {
        const testError = new Error('testing');
        const expectedActions = [{
          type: `${actions.GET_THINGS}_PENDING`
        }, {
          type: `${actions.GET_THINGS}_REJECTED`,
          payload: testError,
          error: true
        }];

        Thing.getThings.returns(Promise.reject(testError));
        return store.dispatch(actions.serviceChecks('1234'))
          .then(
            () => expect(true).to.eql(false, 'getThings should have thrown'),
            () => expect(store.getActions()).to.eql(expectedActions)
          );
      });
    });
  });
});
```

**Comment by andrewmclagan** [comment]
@pburtchaell I'd be happy to write up some testing docs. Wont be for a few weeks as we are pressed at present. 

@tomatau Yes we also created functions to abstract the request cycle boiler plate :)

````javascript
/**
 * Appends REQUEST asyc action type
 *
 * @author Andrew McLagan <andrew@ethicaljobs.com.au>
 */

export function REQUEST(actionType) {
  return `${actionType}_REQUEST`;
}

/**
 * Appends SUCCESS asyc action type
 *
 * @author Andrew McLagan <andrew@ethicaljobs.com.au>
 */

export function SUCCESS(actionType) {
  return `${actionType}_SUCCESS`;
}

/**
 * Appends FAILURE asyc action type
 *
 * @author Andrew McLagan <andrew@ethicaljobs.com.au>
 */

export function FAILURE(actionType) {
  return `${actionType}_FAILURE`;
}
````

**Comment by pburtchaell** [comment]
I recently added tests for to the complex example for the [global error middleware](https://github.com/pburtchaell/redux-promise-middleware/blob/2eb8e73c221b724767f4d14c0afdf7183384f64b/examples/complex/middleware/error.spec.js) and the [async action creators](https://github.com/pburtchaell/redux-promise-middleware/blob/2eb8e73c221b724767f4d14c0afdf7183384f64b/examples/complex/actions/error.spec.js). There is nothing new here in terms of testing strategies, but it could be referenced in the docs.

**Comment by andrewmclagan** [comment]
As a follow on from this.

What are peoples strategies for testing the promise payload of an async action creator?

For example:

````javascript
test('fetchPosts creates correct action', () => {
  const action = fetchPosts({ limit: 10, category: 'blog' });
  expect(action).toEqual({
    type: 'FETCH_POSTS',
    payload: api.get('/posts', { limit: 10, category: 'blog' }),
  });
});
````

This will assert a correct action `{ type }` and fail when it is incorrect.

Although the problem is its not asserting that `api.get(...)` is being called with the correct arguments.

Would I be correct to assume that this is covered by testing how the reducer reacts to the async action types `{ REQUEST, SUCCESS, FAILURE }` the middleware creates? 

Perhaps not because the result of `api.get(...)` is an external influence and is onyl testable through fixtures? Im a little lost :-)

**Comment by nicolechung** [comment]
(Using Jest) I wrote a basic `response` payload:

```
const expectedAction = {
    type: ACTION_NAME,
    payload: {
      status: 200,
      data: {
       // what your response data is
      }
    }
  }
```

And then used "Match Object"...it doesn't have to be exactly like the response as long as it contains the stuff you care about (status code, data)

```
return store.dispatch(fetchLyric())
  .then(() => {
    let actions = store.getActions() // this is an array but my promise just returns one action
    expect(actions[0]).toMatchObject(expectedAction)
  })
```

**Comment by andrewmclagan** [comment]
@nicolechung  ah cool, so create a mock store with the middleware?

**Comment by nicolechung** [comment]
I think so. It's probably a big motivator for people to switch to redux-saga, because with sagas you don't have to mock api calls. 

Api calls - one thing that has tripped me up is that you need different `mock` libraries (is that the word?) depending on what you are using to make your AJAX / api calls.

If you are using `axios` I would recommend using `moxios` to mock your requests and responses.

If you are using `fetch`, `nock` seems to work okay.
