### ISSUE TITLE
Sending data alongside error object

### ISSUE THREAD

**Issue by cubbuk** [pburtchaell/redux-promise-middleware#133]
---

## Version Number
4.2.0

Is there a way to send some data alongside error object similar to sending data during `pending` state for optimistic updates? I have a list of item and I need id of the item to update object with error info during an async operation. Any suggestions how to handle that scenario?

---

**Comment by pburtchaell** [comment]
Can you reject the promise with the `id` of the item?

```js
new Promise((resolve, reject) => {
  reject(new Error(id)); // Reject with the id
});
```

You can also look into custom error types, [which are documented on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error).

**Comment by cubbuk** [comment]
Well in that case I need to update error coming from backend api which might not be trivial but can be done absolutely. I was thinking about a solution similar to optimistic update case where we can send additional error data object while calling the promise. If you think it is useful I might work on a PR?

```
const foo = data => ({
  type: 'FOO',
  payload: {
    promise: new Promise(),
    data: data,
    errorData: errorData
  }
});

// rejected action
{
  type: 'FOO_REJECTED',
  payload: {error, errorData}
}
```

**Comment by pburtchaell** [comment]
My suggestion would be to:

1. Include the `id` in the error, or 
2. include the `id` in the meta.


>  I was thinking about a solution similar to optimistic update case where we can send additional error data object while calling the promise.

The middleware follows [Flux Standard Actions (FSA)](https://github.com/acdlite/flux-standard-action), which won't allow for the structure you are proposing.

**Comment by tomatau** [comment]
If you want to have information about the error in your payload you can't put it in the initial action as the error information isn't available until the promise resolves.

v2.4 allows you to add additional information to the meta of the _REJECTED phase.

**Comment by cubbuk** [comment]
@tomatau Could you give an example of using meta? I don't want to have information about error on initial action, I want to append additional info to error phase from initial action. Thanks

**Comment by tomatau** [comment]
@cubbuk I think that's not possible with the latest API.

Using 2.4 you can do:

```js
const creator = () => ({
  type: 'FOO',
  payload: {
    promise: getStuff()
  },
  // adding meta here will be available in partialAction below
})

const getStuff = () => doSomethingAsync()
  .then(data => data.happy)
  .catch(error => {
     // sad path, first we return a function that will be treated as a thunk with a partialAction
     return (partialAction, dispatch) => {
       // sweet, now we can add meta
       dispatch({
          type: partialAction.type, // FOO_REJECTED
          payload: error,
          meta: { any: 'any information specific to the rejected case' }
       }):
     }
  });
```

**Comment by cubbuk** [comment]
Hmm sad to hear that, thanks.

**Comment by pburtchaell** [comment]
You are able to dispatch `meta` with the rejected action in all versions of the middleware. 

The problem is you will not be able to access information for the error at the time the initial action is dispatched, as @tomatau suggested. This would require the use of thunks, which is available in the v2.x API. 

That being said, there is issue #67 open—if you are interested in working on that, @cubbuk!

**Comment by cubbuk** [comment]
DSL approach seems like a good idea, why is it deleted?

**Comment by tomatau** [comment]
Because you can't access the resolved data in a DSL defined in the initial action object. Also, DSLs tend to introduce magic and often become a bit limited. Verbosity isn't the most pressing problem to solve.

Functions are the way forward!

**Comment by pburtchaell** [comment]
Yeah, the best approach to this would be to just implement the v2 thunk functionality in v4.

The DSLs also won't solve the problem you're having in this issue: the information would be set at the initial action and additional information can't be added later.
