### ISSUE TITLE
chaining redux-actions and redux-promise-middleware

### ISSUE THREAD

**Issue by radziksh** [pburtchaell/redux-promise-middleware#136]
Hi, @pburtchaell. Great middleware! I have a simple question and I didn't found this in documentation. How to use chaining in `redux-promise-middleware` with `redux-actions` ? 
this is question in stackoverflow (for more info): http://stackoverflow.com/questions/41366987/chaining-redux-actions-and-redux-promise-middleware.

**Comment by pburtchaell** [comment]
Closing this because there is an answer on StackOverflow.
