### ISSUE TITLE
The dispatched actions don't need an undefined payload/meta

### ISSUE THREAD

**Issue by AugustinLF** [pburtchaell/redux-promise-middleware#14]
Right now, redux-promise-middleware dispatches actions with the keys meta and payload with an undefined value, even if they were not passed (for instance, the pending action, without any data provided will have an undefined payload).

When testing actions, it forces me to specify the undefined values if I want to use a `deepEqual`. I agree that this is not big problem, but since the [FSA spec](https://github.com/acdlite/flux-standard-action) states that this keys are not necessary, I don't think that redux-promise-middleware should add them.

If you agree, I'll gladly submit a PR.

**Comment by pburtchaell** [comment]
Surely. I do agree with that. I would be very happy to accept a PR! :smile:

**Comment by tomatau** [comment]
This has already been fixed in v2 when adding the promiseTypeSuffixes.

https://github.com/pburtchaell/redux-promise-middleware/blob/master/src/index.js#L24

**Comment by AugustinLF** [comment]
Oh, I'm sorry! But it might not have been done for the data, no? I'll test all that when I'll be able to update my version of the middleware :)

**Comment by tomatau** [comment]
True, the data isn't checked and will go through as undefined. :)

**Comment by pburtchaell** [comment]
It might be good to add some unit tests for this.

**Comment by tomatau** [comment]
On a roll with PRs so made another one for checking whether the data has been populated.

**Comment by pburtchaell** [comment]
@AugustinLF I am going to release this as version 2.1.1. Can you let me know if it works for you? Thanks.

**Comment by AugustinLF** [comment]
Everything works perfectly, thanks a lot!
