### ISSUE TITLE
FULFILLED/REJECTED does not send custom payload data for opportunistic updates

### ISSUE THREAD

**Issue by ftsf** [pburtchaell/redux-promise-middleware#140]
## Version Number
4.2.0
## Code Example
```
function destroyFoo(foo) {
  store.dispatch({
    type: "DESTROY_FOO",
    payload: {
      promise: axios.delete("http://localhost/foo/"+foo.id),
      data: { foo: foo.id },
    }
  })
}
```
## Expected Behavior

In the reducer I want to recieve:
`{ error: true, payload: { payload: { foo: foo.id }, promise: Error..., type: "DESTROY_FOO_REJECTED" }`
Or some way I can access the custom data, ideally without breaking compatibility with existing projects.

Is there suggested way to do this?

## Actual Behavior

In the reducer I recieve:
`{ error: true, payload: Error..., type: "DESTROY_FOO_REJECTED" }`
My custom data is not present in the action.

Same behaviour is present with FULFILLED.

---

**Comment by pburtchaell** [comment]
> FULFILLED/REJECTED does not send custom payload data for opportunistic updates

**This is the expected behavior.** The "custom payload data" (what you would use for optimistic updates) is sent in the pending action, not the fulfilled/rejected action.

Given your example, the pending action should be:

```js
{
  type: "DESTROY_FOO_PENDING",
  payload: {
    foo: '' // the value of foo.id
  }
}
```

This is explained [in the documentation](https://github.com/pburtchaell/redux-promise-middleware/blob/master/docs/guides/optimistic-updates.md).

> [I need to] access the custom data, ideally without breaking compatibility with existing projects.

If you want to include this data in the fulfilled/rejected action, I would suggest  using the `meta` property. 

Given your example action creator, this is how the meta property would be used:

```js
function destroyFoo(foo) {
  store.dispatch({
    type: "DESTROY_FOO",
    payload: {
      promise: axios.delete("http://localhost/foo/"+foo.id),
      meta: { foo: foo.id },
    }
  })
}
```

This should include `foo` on all dispatched actions.

Please let me know if this resolves your issue. If not, I'm happy to help more.

```

**Comment by ftsf** [comment]
Thanks very much, I wasn't aware of the `meta` property, it seems to be missing from the documentation.

Looks like `meta` should be defined outside `payload` otherwise it doesn't seem to be included.

```
store.dispatch({
  type: "DESTROY_FOO",
  meta: { foo: foo.id },
  payload: axios.delete("http://localhost/foo/"+foo.id),
}
```
Seems to do the trick, which seems to make the `data` attribute on `payload` pointless since one can always use the `meta` property. Is there any reason I should use data instead of meta?

Thanks very much for the quick and helpful response.

**Comment by pburtchaell** [comment]
> Thanks very much, I wasn't aware of the meta property, it seems to be missing from the documentation.

The middleware supports [Flux Standard Action (FSA](https://github.com/acdlite/flux-standard-action). The meta property is explained in their documentation.

I did notice however, the docs for this middleware does not mention the FSA standard. I'll update the docs to include a link and a note.

> Looks like meta should be defined outside payload otherwise it doesn't seem to be included.

Correct. That was a typo in my example. Sorry about that! 

> Is there any reason I should use data instead of meta?

When used correctly, an action describes a update to state. If your goal is to make an optimistic update to state, you should use the `data` property and the pending action. 

This action describes an optimistic update:

```js
{
  type: "DESTROY_FOO_PENDING",
  payload: {
    foo: // the value of foo.id
  }
}
```

The meta property, on the other hand, is (according to FSA) "intended for any extra information that is not part of the payload."  You shouldn't use it to describe an optimistic update.
