### ISSUE TITLE
Documentation for 'meta'

### ISSUE THREAD

**Issue by nahushf** [pburtchaell/redux-promise-middleware#150]
Is the use of the `meta` property mentioned anywhere in the documentation. I wanted to pass a few custom arguments through my action, but could not find any documentation pertaining to functionality like this. Finally, I had to go through the source code to figure it out for myself.

**Comment by pburtchaell** [comment]
The project follows [FSA](https://github.com/acdlite/flux-standard-action), which is why you can only use `meta`. I thought the documentation mentioned this, but it looks like that mention was removed in the last major release. I'll add it back soon. Sorry for the headache!

**Comment by pburtchaell** [comment]
Resolved in https://github.com/pburtchaell/redux-promise-middleware/commit/17838557cbb39791064b06894fcccd35119ca56c.
