### ISSUE TITLE
Incompatible with Flow type definition

### ISSUE THREAD

**Issue by ml9951** [pburtchaell/redux-promise-middleware#151]
The current implementation is incompatible with the flow type definition in [flow-type](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/redux_v3.x.x/flow_v0.33.x-/redux_v3.x.x.js).  Specifically, the type definition for [`Dispatch`](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/redux_v3.x.x/flow_v0.33.x-/redux_v3.x.x.js#L10).  This definition states that the return value from `dispatch` must be an Action, but the `redux-promise-middleware` returns a `Promise` instead.

**Comment by tomatau** [comment]
This recommendation was discussed a lot in the redux community but it was agreed that the return from dispatch is only recommended to be an action. Actually the return type should be an "any" http://redux.js.org/docs/api/Store.html#notes
