### ISSUE TITLE
Unit testing async actions with promise middleware

### ISSUE THREAD

**Issue by sreevisakh** [pburtchaell/redux-promise-middleware#155]
I am trying to write unit test cases to my async actions. I am using thunk, promise middleware,  I tried different methods none of the worked.  My action file is as follows
```
export function deleteCommand(id) {
  return (dispatch) => {
    dispatch({
      type: 'DELETE_COMMAND',
      payload: axios.post(`${Config.apiUrl}delete`, { _id: id })
    })
  }
}

```
all the examples in the internet is about fetch, and manually dispatching actions.  in the above scenario how will i test the action?
[Stackoverflow Question](http://stackoverflow.com/questions/43986386/unit-testing-redux-async-actions)

**Comment by pburtchaell** [comment]
Have you tried looking at the tests for [the library](https://github.com/pburtchaell/redux-promise-middleware/tree/master/test)? There is also issue #132, which has an in-depth discussion of testing strategies/methods.
