### ISSUE TITLE
How do I use promiseTypeSuffixes to rename to no suffix?

### ISSUE THREAD

**Issue by FateRiddle** [pburtchaell/redux-promise-middleware#156]
So I set up like this:
```js
applyMiddleware(
  promiseMiddleware({
    promiseTypeSuffixes: ['', 'SUCCESS', 'ERROR']
  })
)
```
In hope that pending state returns the original action type 'TODO'(for optimistic UI stuff), but instead it returns  'TODO_', kinda have to fix every reducer if I implement this middleware, is there a way to just return original action type? If no, could it be in future?

**Comment by pburtchaell** [comment]
By design, this isn't possible with Redux Promise Middleware. A pending
action describes a pending (or temporary) change in state, e.g., an
optimistic update.

However, you could create a middleware that follows Redux Promise
Middleware in the chain and just removes the extraneous `_`.
