### ISSUE TITLE
using ajax， ACTION will be wrong

### ISSUE THREAD

**Issue by lemonleon** [pburtchaell/redux-promise-middleware#158]
## Version Number
4.2.0
## Code Example

```javascript
export const fetchAction = (action, url) => ({
    type: action,
    payload: new Promise((resolve, reject) => {
        // fetch(url).then(response => response.json())
        //     .then(data => {
        //         resolve(data)
        //     })
        //     .catch(err => {
        //         reject(err)
        //     });
        $.ajax({
            url: url,
            datatype: 'json',
            success: function (data){
                resolve(data);
            },
            error: function (err){
                reject(err);
            }
        })
    })
});
```

## Expected Behavior
The ajax method is the same as the result of the fetch method
## Actual Behavior
if using ajax（jQuery@1.8.3）， when REJECTED， It will launch the second request， like this：
ACTION： TEST
TEST_PENDING, TEST_REJECTED_PENDING, TEST_REJECTED_REJECTED_PENDING.
if using fetch， it will be ok： TEST_PENDING, TEST_REJECTED

**Comment by pburtchaell** [comment]
First, both `ajax` or `fetch` return a promise; don't wrap them in a new promise. That's [an anti pattern](https://github.com/petkaantonov/bluebird/wiki/Promise-anti-patterns#the-deferred-anti-pattern).

**Comment by lemonleon** [comment]
but in your examples, fetch in the promise.
this is your code 
```javascript
// Request a post from the API with a 1s delay
const getPost = id => ({
  type: 'GET_POST',
  payload: new Promise(resolve => {
    setTimeout(() => fetch(`/api/posts/${id}`).then(response => {
      resolve(response.json());
    }), 1000);
  })
});
```
Its wrong??  What do I do then, now?

**Comment by pburtchaell** [comment]
The example uses `setTimeout` to simulate a one second response time. That's why there is a new promise constructed. There's a big difference between this example code, which is optimized to demonstrate concepts, and production code, which should be optimized for efficiency. Hope that helps.

**Comment by lemonleon** [comment]
Ok~ if I will fetch some data，how should I write?  Don't wrap that in a new promise，production code.

**Comment by pburtchaell** [comment]
> [...] if I will fetch some data, how should I write?

If you're new to the Fetch API, I would really just suggest [searching the web](https://www.google.com/search?q=fetch+api&oq=fetch&aqs=chrome.2.69i57j0l5.2314j0j7&sourceid=chrome&ie=UTF-8). 

The first four links—MDN, Google Developers Blog, and David Walsh Blog—are good resources.
