### ISSUE TITLE
Default configuration swallows errors thrown in render()

### ISSUE THREAD

**Issue by qrohlf** [pburtchaell/redux-promise-middleware#159]
**summary:**

redux-promise-middleware will silently swallow errors thrown in a component `render()` when the render cycle is triggered by a promise resolving. While the documentation is nice and clear on the issue of rejected promises, it doesn't mention this behavior anywhere.

I would consider this to be a major issue, since it leads to an incredibly frustrating developer experience where your app just fails to function with no errors, stack trace, or any indication that something went wrong. Even Chrome's `uncaught in promise` logging isn't triggered here.

## Version Number
master@ 6965a6df7cb924e4651f35b70ecfd30a817ef43f

## Test Case
I've pushed a minimal reproduction case to https://github.com/qrohlf/redux-promise-middleware/tree/repro_issue

Here's the diff: https://github.com/pburtchaell/redux-promise-middleware/compare/6965a6df7cb924e4651f35b70ecfd30a817ef43f...qrohlf:repro_issue?expand=1

## Steps to Reproduce

1. Clone https://github.com/qrohlf/redux-promise-middleware/tree/repro_issue
2. `yarn install`
3. `yarn start`
4. Open http://localhost:8000/simple
5. Open your browser's developer console
6. Press the 'Get Post' button

## Expected Behavior

I should see an error in my developer console like this:
![screen shot 2017-06-01 at 9 59 43 am](https://cloud.githubusercontent.com/assets/347189/26691571/81135106-46b2-11e7-9f9d-95b0e4a9cbb0.png)

## Actual Behavior

The app crashes and appears stuck to the end-user. No debugging output is presented to the developer.

**Comment by pburtchaell** [comment]
Thanks for the comprehensive PR @qrohlf. I will get to this as soon as possible!

**Comment by pburtchaell** [comment]
Thanks for your patience @qrohlf. I started a new job last week and caught a cold/flu. I'll take a deeper look at this starting today.

**Comment by qrohlf** [comment]
@pburtchaell no worries, we've got a workaround that's working fine for us.

For anyone else running into this, you can lock your redux-promise middleware at `4.2.1` for now to fix the error-swallowing:

![screen shot 2017-06-08 at 11 39 21 am](https://user-images.githubusercontent.com/347189/26944968-2445ee38-4c3f-11e7-8adb-4a9dea048f1f.png)

**Comment by peter-mouland** [comment]
just thinking, if the bug is critical, does it make sense to release `4.3.1` which is the same as `4.2.1` so that everyone on 4.3 gets the fix?  

Seems like it would be quicker to do that than releasing a bug fix?

**Comment by tomatau** [comment]
Hi @peter-mouland :) Yeh that makes sense although it wouldn't follow semver as there would be a regression from the changes that came in 4.3 being lost in 4.3.1

@qrohlf can you check this against version 2.4 please? I'm still activity maintaining it and would like to know the the same problem exists.

**Comment by pburtchaell** [comment]
@peter-mouland yeah, we could to that, but released  as `4.3.1` wouldn't make sense in the version history as we would regress an existing feature, not add a new feature. 

We should have a fix soon, either in the form of reverting #126 or merging #162. Once that's done, I'll release `4.4.0` and consider `4.3.x` fully depreciated to avoid any confusion. I think that makes the most sense for the version history and keeping our releases clear/transparent.

**Comment by pburtchaell** [comment]
Working on a release before the end of the month @leup.

**Comment by leup** [comment]
Thanks for the feedback ! @pburtchaell

**Comment by pburtchaell** [comment]
Resolved in #171, which reverts the changes from #126, and released as `redux-promise-middleware@4.4.1` on npm. Please reopen if you are still experiencing this issue!
