### ISSUE TITLE
Just thank you !!!

### ISSUE THREAD

**Issue by pierre-H** [pburtchaell/redux-promise-middleware#163]
Hi !
I just want to thank @pburtchaell for redux-promise-middleware !
It's a so great package ! It saves me ! It simplify my code and I can easily do chaining actions.
Thank you !

(sorry for opening an issue for that, but I just wanted so much to thank you !)
You can close this issue :)

**Comment by pburtchaell** [comment]
You're welcome! Also thank you to @tomatau and everyone who has made contributions over time. 😄
