### ISSUE TITLE
unhandled rejection (?)

### ISSUE THREAD

**Issue by stevenvachon** [pburtchaell/redux-promise-middleware#167]
I'm confused how we're supposed to prevent an unhandled rejection:
```js
export const signIn = ({email, password}) => ({
  type: 'SIGN_IN',
  payload: http.post('signin', {email, password})
});
```
```js
const initialState = {inProgress: false, isSignedIn: false};

export default (state=initialState, action) => {
  switch (action.type) {
    case 'SIGN_IN_FULFILLED': {
      return {...state, inProgress: false, isSignedIn: true};
    }

    case 'SIGN_IN_PENDING': {
      return {...state, inProgress: true, isSignedIn: false};
    }

    case 'SIGN_IN_REJECTED': {
        const error = action.payload;
        alert(`${error.name}: ${error.message}`);
    }

    default: return state;
  }
};

```

**Comment by stevenvachon** [comment]
According to https://github.com/pburtchaell/redux-promise-middleware/blob/master/docs/guides/rejected-promises.md, we now need to depend on [redux-thunk](https://npmjs.com/redux-thunk)? I switched to this lib to get away from that cruft.

**Comment by stevenvachon** [comment]
I ended up with:
```js
import isPromise from 'is-promise';
import ValidationError from '../util/ValidationError';

// From https://github.com/pburtchaell/redux-promise-middleware/blob/4.3.0/examples/complex/middleware/error.js
export default () => next => action => {
  if (!isPromise(action.payload)) {
    return next(action);
  }

  // Dispatch initial pending promise, but catch any errors
  return next(action).catch(error => {
    if (!(error instanceof ValidationError)) {
      // TODO :: use some kind of flash messaging
      alert(`${error.name}: ${error.message}`);
    }
  });
};
```

…but my build would be better with #169 patched.

**Comment by pburtchaell** [comment]
> I switched to this lib to get away from that cruft.

I would recommend using Redux Thunk so you can access the promise. It's a matter of opinion, but the Redux Thunk + this middleware is a very effective combination. 

What exactly is your issue? #169 has been delayed, but a patch is in the works.

**Comment by stevenvachon** [comment]
My issue was that I needed to write a custom middleware as a result of the v4 changes, to which #168 would be a big improvement. I also don't need thunks as everything is promise/async/await-based.

**Comment by pburtchaell** [comment]
> I also don't need thunks as everything is promise/async/await-based.
 
From your example,`() => next => action => { ... }` is effectively a thunk. 
A thunk is a function that returns another function. Redux Thunk keeps your action creators dry by eliminating what you're writing, but if you prefer to write it, that's your preference. 

Closing this issue to focus on #168.
