### ISSUE TITLE
Option to catch errors

### ISSUE THREAD

**Issue by stevenvachon** [pburtchaell/redux-promise-middleware#168]
It would be very helpful. We are already consuming the error in our reducers.

**Comment by pburtchaell** [comment]
Can you elaborate on this? Are you looking for an option on the middleware config?

**Comment by stevenvachon** [comment]
Yes, an option to catch all errors without the need for a custom middleware. Custom middleware isn't the clearest thing in the world. Perhaps a boolean and/or a callback.

**Comment by pburtchaell** [comment]
This middleware doesn't catch errors by design. The middleware is (1) designed to purely dispatch actions that describe the two promise states (pending and settled) and (2) not designed to handle promise side effects like errors.

**Comment by stevenvachon** [comment]
Yes, I've seen you say/type that a lot, and that design decision is annoying 😛
