### ISSUE TITLE
Use is-promise

### ISSUE THREAD

**Issue by stevenvachon** [pburtchaell/redux-promise-middleware#169]
[is-promise](https://npmjs.com/is-promise)

Less redundancy. When we need to write our own middleware to catch errors not caught by this library, we can simply import the same dependency.

**Comment by pburtchaell** [comment]
I'd prefer not to add a dependency to the project.

**Comment by stevenvachon** [comment]
Why? Dependencies are good. They prevent unnecessary tests.
