### ISSUE TITLE
Release notes don't mention required change when calling applyMiddleware

### ISSUE THREAD

**Issue by esseb** [pburtchaell/redux-promise-middleware#17]
In 2.0.0 the middleware must now be initiliazed like this:
```
composeStoreWithMiddleware = applyMiddleware(
  promiseMiddleware()
)(createStore);
```

Previously it was:
```
composeStoreWithMiddleware = applyMiddleware(
  promiseMiddleware
)(createStore);
```

The `()` isn't mentioned in the release notes and it took me a while to figure out what the problem was.

**Comment by tomatau** [comment]
Thanks for pointing this out! I've updated the release notes with the API change.

**Comment by esseb** [comment]
Great, thanks.

**Comment by steida** [comment]
Where I can like this comment? Thank you : )
