### ISSUE TITLE
Rejecting promises not always an error

### ISSUE THREAD

**Issue by mpolichette** [pburtchaell/redux-promise-middleware#173]
I suppose this is a feature request, but I feel like it is wrong to blanket assume all rejected promises are error cases.  Sometimes you don't have permissions to do something, but its not actually an error case. 

I've read through old issues and the documentation and it appears the project tries to work around the issue cause by throwing errors by encouraging a custom wrapping middleware.  My argument would be that the error throwing is only adding extra complexity to this project and making it harder for users to use.

I think a simpler approach would be to just not throw errors in the first place.  Users will still have the ability to throw their own error from their action creators as well have the ability to use a promise rejection as a viable code path to perform some update to their stores.

### An example:
I allow partial access to device information if a user is not logged in.  When the user requests this info, if they have permissions to access it, I'd like to resolve to the device info.  If they don't have access, I'd like to reject, but still give the partial info.  

I feel those are the write semantics for the and my reducers can work on both `GET_DEVICE_INFO_FULFILLED` and `GET_DEVICE_INFO_REJECTED` to store the info.  I know there are other solutions, including `.catch`ing and dispatching a new action (or even mocked `GET_DEVICE_INFO_REJECTED`).  

Note: This all works with the current implementation, the only issue is that this middleware also throws an error which goes uncaught. 

Anyway, I can understand if this is contrary to the intention of this project or would break too much backwards compatibility.  I am not blocked by the current implementation. 

A couple implementation ideas, 
1. Remove throwing -> major version bump
1. Provide a `action.meta` value which prevents throwing errors.  This would retain backwards compat while allowing a simple prevention of error being thrown.
1. Make error throwing configurable during init `promiseMiddleware({ throwOnRejection: false})`

Anyway, thanks for the awesome project, and your consideration!

## Version Number
v4.3.0
### Action
```
dispatch({ type: 'ACCESS_SECURE_THING', payload: new Promise((resolve, reject) => {
  if(userHasAccess()) { 
    resolve(thing)
  } else {
    reject(partialThing)
  }
})
```

### Reducer
```
const reducer = (state, action) => {
  switch(action.type){
    case 'ACCESS_SECURE_THING_FULFILLED': { // store thing }
    case 'ACCESS_SECURE_THING_REJECTED': { 
      ...
      // store partial thing and set flag for limited access }
   }
}
```

## Expected Behavior
No error thrown

## Actual Behavior
Error thrown

**Comment by MrCrunchwrap** [comment]
https://github.com/pburtchaell/redux-promise-middleware/blob/master/docs/guides/rejected-promises.md

An uncaught promise rejection *should* throw an error. It's not the middleware's job to catch errors for you. You can still pass values through your reject that will make it to the _REJECTED action. The values you reject with will be on the payload of your action, available to the reducer.

**Comment by pburtchaell** [comment]
> it appears the project tries to work around the issue cause by throwing errors by encouraging a custom wrapping middleware

Actually, the middleware does not throw errors. When a promise is rejected, the promise throws an error. That error is passed through the middleware and it's the developer's responsibility to catch the middleware either in an async action creator or in middleware.
