### ISSUE TITLE
Handle async functions while providing thunk-like functionality

### ISSUE THREAD

**Issue by mikew** [pburtchaell/redux-promise-middleware#175]
First off, really love this package. I've been using it on all my redux projects for years.

I do have a feature request though. Now that async / await is more popular, and while it technically is already supported via IIFE:

```javascript
{
  payload: (async function () { ... })()
}
```

It would be cool if this package just supported the `promise` attribute being a function, and if the result of that function was a promise (i.e has `typeof then === 'function'`), treat that as the regular promise payload.

And as a bonus, `dispatch` and `getState` could be supplied from the store, so what was:

```javascript
function myAction () {
  return (dispatch, getState) => {
    return dispatch({
      type: 'MY_ACTION',
      payload: {
        promise: (async function () {
          const result = await someApiCall()
          dispatch(someOtherAction())

          return result
        })()
      }
    })
  }
}
```

could become:

```javascript
function myAction () {
  return {
    type: 'MY_ACTION',
    payload: {
      async promise (dispatch, getState) {
        const result = await someApiCall()
        dispatch(someOtherAction())

        return result
      }
    }
  }
}
```

**Comment by pburtchaell** [comment]
This is released as `redux-promise-middleware@5.0.0` on npm.

**Comment by MrCrunchwrap** [comment]
I was trying to implement this middleware in my project where all my actions are already using async/await, but I'm not clear on something. Using the second syntax provided by @mikew where does the value of `dispatch` come from?

```javascript
function myAction () {
  return {
    type: 'MY_ACTION',
    payload: {
      async promise (dispatch, getState) {
        const result = await someApiCall()
        dispatch(someOtherAction())

        return result
      }
    }
  }
}
```

When I write my actions like this, dispatch is not defined and so I have no ability to dispatch other actions from my async function. If I convert them back to regular thunks, they work fine and receive `dispatch` from the outermost function, just like the first example.

**Comment by mikew** [comment]
Those features were dropped, based on the discussion at https://github.com/pburtchaell/redux-promise-middleware/pull/176#issuecomment-342309786.
