### ISSUE TITLE
Allow empty separator

### ISSUE THREAD

**Issue by tiagobnobrega** [pburtchaell/redux-promise-middleware#177]
I'm not sure if it's Bug or a feature request.
I would like the ability to use empty (blank string) as separator. The idea is to disable separator appending. 

Here's the main idea:
I would configure the middleware like this:

```javascript
promiseMiddleware({
  promiseTypeSeparator:"",//do not use separators, we append manually for status success and fail
  promiseTypeSuffixes: ['', '_SUCCESS', '_FAIL']
});
```
Then, when I call "FETCH_THING" action. It would dispacth the "FETCH_THING" action immediately,  "FETCH_THING_SUCCESS" on fulfilled and "FETCH_THING_FAIL" on error .

As it is now. It would use the default separator "_".

I think it could be acomplished by changing this on promiseMiddleware function:

```javascript
function promiseMiddleware() {
  var config = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};

var promiseTypeSuffixes = config.promiseTypeSuffixes || defaultTypes;
//var promiseTypeSeparator = config.promiseTypeSeparator || '_';
var promiseTypeSeparator = (config.promiseTypeSeparator ==null ? '_': config.promiseTypeSeparator )
...
```
PS: Code not tested.
EDITED: Ops... Corrected wrong variable.

**Comment by pburtchaell** [comment]
Sorry, but this isn't a paradigm we'll support with this middleware. 

It's good design to be specific and descriptive with the name of your actions. Because the promise is in a pending state, `FETCH_THING_PENDING` is accurate than `FETCH_THING`.

**Comment by tiagobnobrega** [comment]
I get your point... but it also bothers me a little that the original action never gets fired to my reducers. Do you think it could be possible to at least dispatch the original action to the reducers?

**Comment by pburtchaell** [comment]
You could write a middleware that runs before this middleware and dispatches a duplicate of your original action.
