### ISSUE TITLE
Include .js in import statements for the browser

### ISSUE THREAD

**Issue by bennypowers** [pburtchaell/redux-promise-middleware#178]
Hello!

Would it be possible to add the `.js` extention to the statement

```js
import isPromise from './isPromise';
```

in dist/es/index.js? browsers need an absolute path to a file in order to resolve modules. If this change were made, browsers could import this module without any build step.

**Comment by pburtchaell** [comment]
Hi! Yes, it would make sense to include the `.js` extension. Feel free to make a PR implementing this.
