### ISSUE TITLE
ACTION_FULFILLED is being dispatched even though the payload promise is being rejected

### ISSUE THREAD

**Issue by Ivo-Yankov** [pburtchaell/redux-promise-middleware#185]
If the promise is rejected and the error is caught, then the middleware dispatches a _FULLFILLED action. Shouldn't a _REJECTED action be dispatched in this case?
If the error is not caught, the resulting action is _REJECTED, but then the error is left uncaught. What is the correct way to get a _REJECTED action?

## Version Number
5.0.0

## Code Example
```
dispatch({
        type: "SOME_ACTION",
        payload: new Promise( (resolve, reject) => {
            reject('some reason');
        })
            .catch( (e) => {
                console.log(e)
            })
    });
```

## Expected Behavior
Dispatch a SOME_ACTION_REJECTED action

## Actual Behavior
SOME_ACTION_FULFILLED is being dispatched

**Comment by tomatau** [comment]
the catch prevents the rejection from propagating. When you do `.then` or `.catch` you're actually creating a completely new promise which is evaluated. Here the new promise will just resolve with undefined after the catch.

**Comment by pburtchaell** [comment]
Yep! If you want to handle promise errors at the action creator level, you need to do so _after_ the action has been dispatched + handled by the middleware. See [the examples in the guide]( https://github.com/pburtchaell/redux-promise-middleware/blob/master/docs/guides/rejected-promises.md).
