### ISSUE TITLE
Testing chained actions inside integration tests with Axios

### ISSUE THREAD

**Issue by priley86** [pburtchaell/redux-promise-middleware#193]
## Version Number
^5.0.0

## Code Example
Hi, thanks so much for this terrific middleware. I believe I am approaching a test case that has not been mentioned here and would really appreciate some advice. This will impact the way we do test cases a lot going forward potentially at Red Hat, Inc. (as promise-middleware has made the cut in our current fold 😄 )

I'm currently attempting to write integration tests whereby actions/reducers are fully run (my actions are hooked via axios responses) and then I am asserting snapshots on the reduced connected component state. I've noted that the redux-mock-store will not accept reducers, so an alternative path I've attempted is using a "real" Redux store and and wiring everything up like I do normally...

This all works fine for a single initial action being fired (dispatched) and I am able to receive the incoming state. However, if I want to fire subsequent actions in my integration test, the Redux store does not dispatch them...

Here is the full test case I have now:
```
import React from 'react';
import thunk from 'redux-thunk';
import promiseMiddleware from 'redux-promise-middleware';
import { createStore, applyMiddleware, combineReducers } from 'redux';
import { mount } from 'enzyme';
import { Provider } from 'react-redux';
import { initialState } from '../overview.fixtures';
import Overview from '../Overview';
import OverviewContainer, { reducers } from '../index';

import { coreComponents } from '../../../../../components';
import componentRegistry from '../../../../../components/componentRegistry';

jest.mock('../../../../../components/componentRegistry');
componentRegistry.registerMultiple(coreComponents);

describe('Overview integration test', () => {
  const middlewares = [thunk, promiseMiddleware()];
  const generateStore = () =>
    createStore(
      combineReducers({ ...reducers }),
      {
        overview: initialState
      },
      applyMiddleware(...middlewares)
    );

  const mountComponent = store =>
    mount(
      <Provider store={store}>
        <OverviewContainer />
      </Provider>
    );

  it('should mount the Overview with mapStateToProps reduced', () => {
    const store = generateStore();
    const wrapper = mountComponent(store);

    // query the unconnected component to assert reduced props
    const component = wrapper.find(Overview);

    expect(component.props()).toMatchSnapshot();
  });
});
```

Snapshot (of reduced initial state):

```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`Overview integration test should mount the Overview with mapStateToProps reduced 1`] = `
Object {
  "hideMappingWizard": false,
  "hidePlanWizard": false,
  "mappingWizardVisible": false,
  "planWizardVisible": false,
  "showMappingWizardAction": [Function],
  "showPlanWizardAction": [Function],
}
`;
```

All of this code can currently be found here:
https://github.com/priley86/miq_v2v_ui_plugin/blob/master/app/javascript/react/screens/App/Overview/__test__/index.test.js

I know there are examples of how to mock the store and the store's dispatch in this projects sample tests w/ Sinon, however those aren't very familiar to me....

Would someone be willing to get a few examples w/ axios / Jest and show how to correctly mock store and integrate subsequent actions?

P.s. I have had no troubles testing Actions individually w/ redux-mock-store...and that much is working great ;)

Those are looking like this:
```
import configureMockStore from 'redux-mock-store';
import thunk from 'redux-thunk';
import promiseMiddleware from 'redux-promise-middleware';
import * as actions from '../MappingWizardClustersStepActions';
import {
  initialState,
  requestSourceClustersData,
  requestTargetClustersData
} from '../mappingWizardClustersStep.fixtures';
import {
  mockRequest,
  mockReset
} from '../../../../../../../../../common/mockRequests';

const middlewares = [thunk, promiseMiddleware()];
const mockStore = configureMockStore(middlewares);
const store = mockStore(initialState);

afterEach(() => {
  store.clearActions();
  mockReset();
});

describe('mappingWizard actions', () => {
  it('should fetch source clusters and return PENDING and FULFILLED action', () => {
    const { fetchSourceClustersUrl } = requestSourceClustersData;
    mockRequest({
      fetchSourceClustersUrl,
      status: 200
    });
    return store
      .dispatch(actions.fetchSourceClustersAction(fetchSourceClustersUrl))
      .then(() => {
        expect(store.getActions()).toMatchSnapshot();
      });
  });
  it('should fetch source clusters and return PENDING and REJECTED action', () => {
    const { fetchSourceClustersUrl } = requestSourceClustersData;
    mockRequest({
      fetchSourceClustersUrl,
      status: 404
    });
    return store
      .dispatch(actions.fetchSourceClustersAction(fetchSourceClustersUrl))
      .then(() => {
        expect(store.getActions()).toMatchSnapshot();
      });
  });
```

## Expected Behavior
This is not a bug. Just a request for documentation examples.

**Comment by pburtchaell** [comment]
Hi @priley86, thanks for the detailed issue and I'm glad to see Red Hat is using the middleware. 😄 

Unless @tomatau beats me to it, I'll take a detailed look at this either over the weekend or next early next week and get back to you. I'm locked down with work for the next few days.

**Comment by pburtchaell** [comment]
In the meantime, if you haven't already, looking at [our tests for the middleware](https://github.com/pburtchaell/redux-promise-middleware/blob/master/test/index.spec.js) _might_ be helpful.

**Comment by priley86** [comment]
thanks @pburtchaell - yea i understand the concepts there, but I'm struggling w/ how to map those to axios. Your help is much appreciated here...

**Comment by pburtchaell** [comment]
@priley86 I've taken an initial look at this, but I can't make any suggestions or go anywhere with it since the example code is so closely tied to your project. 

I'll need you to reproduce the issue in a more isolated environment—something not so tied to the https://github.com/priley86/miq_v2v_ui_plugin repo. A good start would be to fork this repo, set up your test environment using [the complex example](https://github.com/pburtchaell/redux-promise-middleware/tree/master/examples/complex) and make a PR. Even if the tests aren't running, this is a better environment for me to debug your setup.

Let me know if you have any questions.

**Comment by priley86** [comment]
@pbuertchaell sure, happy to do this...I’ll setup a codesandbox when I get a chance. Thanks!

**Comment by pburtchaell** [comment]
@priley86 any progress here?

**Comment by priley86** [comment]
@pburtchaell apologies (have been swamped). I will try to get you a codesandbox later today or tomorrow ;)

**Comment by tomatau** [comment]
Personally for running integration tests I take a step back away from the details of actions, reducers, etc... and focus on hitting routes or events in my application then spy on the network traffic using things like sinon's xml server or libraries like `fetch-mock`. This way if the implementation changes, the integration test can stay exactly the same. I do this A LOT. So much I even presented about it:

https://www.youtube.com/watch?v=8gIAeEVZfJ4&t=213s

**Comment by pburtchaell** [comment]
Hi all, I'm following up on this issue since it's grown stale. I'm going to close it, but if you'd like to revisit it, please just reopen it.

**Comment by priley86** [comment]
Thanks and apologies for not being able to fit this into my schedule. I will provide a better description /demo boiler next time when we are ready on this side 👍
