### ISSUE TITLE
Promise.all FULFILL order

### ISSUE THREAD

**Issue by greeksolid** [pburtchaell/redux-promise-middleware#196]
# Version Number

^4.4.1

# Code Example

Hi first time posting here and I was hoping you could help me with a little problem I am having with the order that Promises get fulfilled.

```
return dispatch => {
    return dispatch({
      type: "FETCH_REGISTER_FORM_DEPENDENCIES",
      payload: Promise.all([
        dispatch(fetchCountries()),
        dispatch(fetchBaseCategories()),
        dispatch(fetchSecondaryCategories()),
        new Promise(resolve => setTimeout(resolve, 1))
      ])
    });
  };
```

The problem is that FETCH_REGISTER_FORM_DEPENDENCIES is fulfilled before the three promises inside payload get fulfilled if I don't add the fake 1ms promise. 
Could you please tell me what I am doing wrong?

**Comment by pburtchaell** [comment]
I've added an example of how to use `Promise.all` in this PR: https://github.com/pburtchaell/redux-promise-middleware/pull/198.

https://github.com/pburtchaell/redux-promise-middleware/blob/8c37fa8ac0f451a32a6f1a9dd7658837a3e1d617/examples/promise-all/index.js#L4-L22

There may be an issue with your middleware order. Can you post your store config too?

**Comment by pburtchaell** [comment]
Glad you got it.
