### ISSUE TITLE
type-to-reducer and promiseTypeDelimiter

### ISSUE THREAD

**Issue by plandem** [pburtchaell/redux-promise-middleware#197]
I know this issue is more related to 'type-to-reducer', but it's better to update readme, because right now 'type-to-reducer' is working only with default delimiter.

**Comment by pburtchaell** [comment]
Yeah, we can add a note to the docs. @plandem, would you be interested in making a PR with the change?

@tomatau maybe it's worth updating the Type to Reducer lib to support custom delimiters? If you don't have time I might be able to do it in a couple of weeks.

**Comment by tomatau** [comment]
No probs, day off work with illness so I threw something together https://github.com/tomatau/type-to-reducer/releases/tag/v1.1.0

https://github.com/tomatau/type-to-reducer/tree/v1.1.0#custom-type-delimiter

**Comment by plandem** [comment]
@tomatau Looks like still need some more work: a) update index.d.ts and b) it's supposed to call this setTypeDelimiter BEFORE using 'type-to-reducer' to create reducers. E.g.:
```
function configureStore(initialState = {}) {
  const promiseTypeDelimiter = '/';
  setTypeDelimiter(promiseTypeDelimiter);
  const promiseMiddleware = createPromiseMiddleware({ promiseTypeDelimiter });
...
}
```

will not work for any imports from root reducers.

**Comment by tomatau** [comment]
@plandem I don't do TS so wouldn't know how to update the TS definition.

Also in the readme it already states `"This will set it for every reducer you create after the custom delimiter is set"`

**Comment by plandem** [comment]
I see. I will PR for d.ts

**Comment by pburtchaell** [comment]
nice @tomatau 😄 

I've updated the docs here in PR https://github.com/pburtchaell/redux-promise-middleware/pull/199.

**Comment by pburtchaell** [comment]
I'm closing the issue here since the docs are updated.
