### ISSUE TITLE
Consider updating to Redux 1.0 RC

### ISSUE THREAD

**Issue by gaearon** [pburtchaell/redux-promise-middleware#2]
Redux 1.0 RC is out with breaking changes. **No further API changes are expected in 1.0 so it may be a good time to port the repo to 1.0 RC (in a branch).** We will release 1.0 when the docs are ready.

You can find the comprehensive list of the changes in 1.0 RC against 1.0 alpha in the **[Redux 1.0 RC release notes](https://github.com/gaearon/redux/releases/tag/v1.0.0-rc)**. If you haven't ported to alpha yet, you'll need to **[apply changes from 0.12 to alpha first](https://github.com/gaearon/redux/pull/195#issue-92206321)**.

Thank you!
Please make sure to report any issues so we can release a stable 1.0.

**Comment by kuuup** [comment]
I made a pull request. As far as I can see only a tiny change was needed.

**Comment by pburtchaell** [comment]
:+1: I'm going to test everything out today and make a release.

**Comment by pburtchaell** [comment]
Alright released as `redux-promise-middleware@0.1.0`.
