### ISSUE TITLE
[Question] publishing the package

### ISSUE THREAD

**Issue by franklixuefei** [pburtchaell/redux-promise-middleware#211]
Hi,

Just one question - when you published your package, did you use `npm publish`? I asked because I want to publish a package myself, and it also has `index.d.ts` under the project root, but after publishing the package, I didn't see `index.d.ts` anywhere under `node_modules/myPackage/` after I pulled my published package from another project. So, when you published the package after I added the `index.d.ts`, did you do anything special? Could you share your publish script with me?

Thanks a lot!

**Comment by pburtchaell** [comment]
Hi there! I'm not doing anything special to publish the package, actually. I just use `npm publish`.

If you check this package's package.json, there is a `npm run build` script that I run as a prepublish script. This runs a few different builds with Babel and WebPack. Once the builds are done and tests pass, the files are uploaded to npm. 

There is also an npmignore file, which specifies to npm if there are any files that should not be uploaded. This is useful for redundant files like `CONTRIBUTING.md` or the tests. These files aren't really used by consumers of the package, so npm doesn't upload them.
