### ISSUE TITLE
Question regarding catching error on dispatcher or handling it in reducer with _REJECTED

### ISSUE THREAD

**Issue by john-raymon** [pburtchaell/redux-promise-middleware#224]
I asked this question on stackoverflow, figured someone might see it here and may be able to help out.

[Stackoverflow question](https://stackoverflow.com/questions/51760408/should-i-also-catch-errors-on-my-dispatch-in-redux-promise-middleware-or-ignore)

**Comment by pburtchaell** [comment]
I just responded on SO. Thanks for asking the question! For future reference, I do get email notifications when people post questions on SO--not necessary to post in both places 😉
