### ISSUE TITLE
How to use the returned promise in typescript?

### ISSUE THREAD

**Issue by stefvw93** [pburtchaell/redux-promise-middleware#225]
I asked this question on overflow a while ago, but didn't get any response, so I'm asking here now. 

https://stackoverflow.com/questions/51544320/how-to-handle-the-return-type-of-dispatch-with-redux-promise-middleware

**Comment by pburtchaell** [comment]
I don't use TypeScript (TS) on a regular basis and can't give you an expert answer.

> Typescript expects returned properties like `payload` and `type`, which are actually not returned because the promise has been handled already and has ACTUALLY been returned

If TS expects `fetchAllUsers` to return a `fetchAction` object , can you change the type so TS expects `fetchAllUsers` to return a promise object? 

```
    export default class ActionCreators {
      public static fetchAllUsers(): FetchAction {
        return {
          type: actionTypes.FETCH_ALL_USERS,
          payload: fetch("api.com/users")
        };
      }
    }
```

**Comment by pburtchaell** [comment]
Something like: 

```
 Promise<any>
```

You might have luck here:

- https://github.com/Microsoft/TypeScript/issues/7588
- https://github.com/Microsoft/TypeScript/issues/14871
