### ISSUE TITLE
Update docs with custom type suffixes page

### ISSUE THREAD

**Issue by dantewebmaster** [pburtchaell/redux-promise-middleware#228]
Example: _FETCHING_ASYNC
Use: 'GET_RESPONSE_FETCHING_ASYNC'

**Comment by pburtchaell** [comment]
Yes, looks like it's not in the documentation anymore, but there is:
https://github.com/pburtchaell/redux-promise-middleware/blob/4.4.0/docs/guides/custom-suffixes.md

I will update the docs to fix this.
