### ISSUE TITLE
Question about a pattern for handling an optimistic update that is rejected

### ISSUE THREAD

**Issue by sstorie** [pburtchaell/redux-promise-middleware#23]
I am using this library in the context of a CRUD application, and so far it does what I need, so thanks for creating it :)

However, I have a question about how to handle an optimistic update that is rejected, and should be rolled back. Please help me if I'm just misunderstanding something, but imagine I have the following scenario:

1. A user edits some entity in the application, and wishes to save it (using an API)
2. We dispatch an "update" action that includes a promise and the new entity as the 'data' property
3. We handle the _PENDING action in the reducer and apply the optimistic update to the state tree (note, at this point I have now lost the previous state for the affected entity)
4. The promise is then rejected so how can I restore the affected entity back to what it was? 

I think there's a simple pattern I just don't see yet, but how are others handling a case like this? Do I need to capture the original entity in my action creator and dispatch some other action in the result of a failure to "roll back" my optimistic update?

Thanks for any guidance!

**Comment by tomatau** [comment]
Hey @sstorie

So you're totally correct with the first 3 points.

In point four, currently according to FSA, when rejecting the promise, you can reject with an Error object or something along those lines. Promise middleware will then dispatch a `_REJECTED` action type with whatever you returned/resolve in your rejected promise and set that as the payload.

This _REJECTED payload should contain the information about the item(s) that need(s) rolling back and so the reducer will just perform the state rollback in the _REJECTED handler.

Another option is to supply meta information that will be consistent with all action type suffixes which the _REJECTED handler can read to perform the rollback, but I personally find an error payload to be more explicit.

**Comment by sstorie** [comment]
Ok, so I'm using this in an Angular/Typescript application, and here's what I've come up with for handling this inside an action creator service. I think I need to wrap the http promise with my own so I can modify what's returned when it succeeds or fails (this is part of what I was not understanding earlier):

```javascript
    updateModelAsync(updatedModel: models.MyModel, originalModel: models.MyModel): void {
        let deferred = this.$q.defer();

        // Create the action using this wrapping promise and pass the updated model as optimistic data
        //
        let action = createAsyncAction(
            actions.UPDATE_MODEL,
            deferred.promise,
            updatedModel);

        this.$http.put<models.MyModel>("/my/api/", updatedModel)
            .success((response: models.MyModel) => {
                // Do other work related to this action

                // Resolve our wrapping promise with this result so it's passed down the pipeline
                //
                deferred.resolve(response);
            })
            .error((error: any) => {
                // Do specific error handling stuff here

                // Reject our wrapping promise with the original fixture so it's passed down the pipeline
                //
                deferred.reject(originalFixture);
            });


        this.$ngRedux.dispatch(action);
    }
```

This might be a bit simplistic because I'm not passing along any error details with the rejected promise, but this could be modified to do something like that.
