### ISSUE TITLE
Add helpers that add suffixes to action types

### ISSUE THREAD

**Issue by futpib** [pburtchaell/redux-promise-middleware#246]
## Problem

When using `redux-promise-middleware` I always end up having to define 3 helper function for each generated action type (for each promise state) like this:

```js
export const pending = actionType => actionType + '_PENDING';
export const fulfilled = actionType => actionType + '_FULFILLED';
export const rejected = actionType => actionType + '_REJECTED';
```

I can then define one action creator (comes with one action type):

```js
export const actions = createActions({
	getProfile: null,
});
```

And use the helpers in a reducer to handle each action generated by `redux-promise-middleware`:

```js
const reducer = combineReducers({
	loading: handleActions({
		[pending(actions.getProfile)]: () => true,
		[fulfilled(actions.getProfile)]: () => false,
		[rejected(actions.getProfile)]: () => false,
	}, initialState.loading),
});
```

Note: [`createActions`](https://redux-actions.js.org/api/createaction#createactionsactionmap) and [`handleActions`](https://redux-actions.js.org/api/handleaction#handleactionsreducermap-defaultstate) are from `redux-actions`.

## Solution(s)

`redux-promise-middleware` should export `pending`, `fulfilled`, and `rejected` functions shown above. Maybe under more descriptive names or as a single object with 3 methods.

## Alternatives

* User has to define helper function for himself
* A separate package could provide the helpers
* User has to explicitly define 3 additional action types for each promise action

**Comment by pburtchaell** [comment]
Hi @futpib~ Thanks for the feedback and great issue. By principle, we've not added any helpers because the middleware should be agnostic to how you implement action creators and reducers. The middleware should only be responsible for accepting a promise and dispatching actions. I agree, helper functions can be useful. However, we believe this should belong in a separate package. 

If you'd like to add a page to the documentation with some suggestions/tips for other developers, please feel free to make a PR!

**Comment by futpib** [comment]
> By principle, we've not added any helpers because the middleware should be agnostic to how you implement action creators and reducers. The middleware should only be responsible for accepting a promise and dispatching actions.

This middleware enforces a convention on action types (and thus on how you implement action creators and reducers) precisly by dispatching actions with generated types. How is this an argument against helpers?
