### ISSUE TITLE
Completely new dispatch for _FULFILLED and _REJECTED

### ISSUE THREAD

**Issue by tomatau** [pburtchaell/redux-promise-middleware#25]
Currently we call `next()` inside the middleware for either rejected or fulfilled actions.

Say you want the _FULFILLED action to return a thunk for whatever reason, now we have some issues where the order or configured middleware limits this possibility. Alternatively you may need thunk actions to later dispatch promises! Right now we can't get both of these middleware to communicate without adding one of these middleware to our store configure twice.

An easy solution to this is to fire a completely new `store.dispatch` per _FULFILLED or _REJECTED instead of calling `next`.. this way other middleware inserted before promiseMiddleware can be applied to the _FULFILLED or _REJECTED action types.

**Comment by pburtchaell** [comment]
Ok, this is released in `redux-promise-middleware@2.2.1`. Closing.
