### ISSUE TITLE
Upgrade URL (docs.psb.codes) is 404'ing

### ISSUE THREAD

**Issue by broofa** [pburtchaell/redux-promise-middleware#251]
This URL (mentioned in log message about upgrading) is 404'ing 
https://docs.psb.codes/redux-promise-middleware/upgrade-guides/v6

**Comment by pburtchaell** [comment]
Fixed in #252. Just need to push to npm. Thank you for the heads up!

**Comment by pburtchaell** [comment]
Released as `redux-promise-middleware@6.1.1`.
