### ISSUE TITLE
TypeScript: fulfilled action result from dispatch

### ISSUE THREAD

**Issue by Vovan-VE** [pburtchaell/redux-promise-middleware#253]
Hello! :wave: 

https://github.com/pburtchaell/redux-promise-middleware/blob/54a1444db8ff0f2f5ca0d174461c29d0eb1dd4d9/src/index.js#L179

This resolve value for `dispatch()` is not declared for TypeScript.

I'm using `redux-promise-middleware` with `react-redux` and `redux-thunk`, and I cannot find the way to get the `{ value }` type definition in `dispatch(...).then()`.

## Version Number
* `redux`: 4.0.1
* `redux-promise-middleware`: 6.1.1

* `react-redux`: 6.0.1

**Comment by pburtchaell** [comment]
Hi! Could you provide an example of (1) your TS code and (2) the desired
change (e.g., how you'd like to use the new type)?

**Comment by pburtchaell** [comment]
Hi! Could you provide an example of (1) your TS code and (2) the desired change (e.g., how you'd like to use the new type)?

**Comment by Vovan-VE** [comment]
Didn't mention:

* `redux-thunk`: 2.3.0

---
I suppose I do something completely wrong. But I cannot find the solution.

There is an action `asyncAction1()` which performs some is API request. It is POST API request to create an object. The API response contains a new created model including it's `id`, for example.

I need to finish dispatching `asyncAction1()` and use the `id` mentioned above in some way. I did such things before in JS:

```js
dispatch(asyncAction1()).then(({ value }) => {
  // do something with value.id
  console.log(value.id);
});
```

But now in TypeScript I cannot do so.

```ts
import { AsyncAction } from 'redux-promise-middleware';

const FOO_BAR = 'FOO_BAR';

interface FooBar {
  id: number;
}

interface FooBarAction extends AsyncAction {
  type: typeof FOO_BAR;
  payload: Promise<FooBar>;
}
```

The problem:

```ts
import { ThunkAction } from 'redux-thunk';
import { AppState } from 'store/';

const sendFooBar = (): FooBarAction => ({
  type: FOO_BAR,
  payload: Promise.resolve({ id: 42 }),
});

const fooBar = (): ThunkAction<void, AppState, null, FooBarAction> => (
  dispatch,
  getState,
) => {
  dispatch(sendFooBar()).then(() => {});
  // --------------------^
  // `dispatch(sendFooBar())` is `FooBarAction`
  // due to current `ThunkAction` .d.ts
};
```

To solve the problem either `sendFooBar()` itself should to return `ThunkAction<Promise, ...>`, or `ThunkDispatch` in `redux-thunk` should be updated to define another return value without loop back to `ThunkAction`.
However, neither `redux-thunk` allows this, nor `redux-promise-middleware` has the type of object, which is actually returned from `dispatch(someAsyncAction())`:

```ts
type FulfilledDispatchResult<A extends AnyAction, R = any> = {
    action: A;
    value: R;
};
```

**Comment by Vovan-VE** [comment]
Something like following could solve the problem:

```ts
interface AsyncAction<R = any> extends Action {
  payload: Promise<R>;
}

type AsyncActionResult<A> = A extends AsyncAction<infer R> ? R : never;

type FulfilledDispatchResult<A extends AsyncAction> = {
  action: A;
  value: AsyncActionResult<A>;
};

interface AsyncThunkDispatch<S, E, A extends Action>
  extends ThunkDispatch<S, E, A>
{
  <A extends AsyncAction>(asyncAction: A): Promise<FulfilledDispatchResult<A>>;
}
```

now:

```ts
const foo = (): AsyncAction<number> => ({
  type: 'FOO',
  payload: Promise.resolve(42),
});

// ...

dispatch(foo()).then(({ value }) => {
  // value is number
});
```

**Comment by tingc10** [comment]
+1, I spent hours looking for type declarations from both `redux-thunk` and `redux-promise-middleware` but couldn't find anything. I ended up creating a custom interface similar to the one @Vovan-VE posted.

**Comment by pburtchaell** [comment]
Adding the help wanted label. This makes sense @Vovan-VE. Please feel free to make a PR!

**Comment by Vovan-VE** [comment]
Well, I have no good idea for this:
```ts
import { ThunkDispatch } from 'redux-thunk';

interface AsyncThunkDispatch<...> extends ThunkDispatch<...> { ... }
```
because it's a special case of conjunction with `redux-thunk`.

**Comment by wulucxy** [comment]
@Vovan-VE how do you solve this?

**Comment by Vovan-VE** [comment]
@wulucxy , see [comment above](#issuecomment-510301369). Also `redux-saga` can achieves the same tasks as both `redux-thunk` and `redux-promise-middleware`, but in the other way.

**Comment by wulucxy** [comment]
@Vovan-VE thanks for your reply。
this is my question：
https://github.com/pburtchaell/redux-promise-middleware/issues/255

can you see any relation with you solution？

**Comment by Vovan-VE** [comment]
Finally, I use following declaration in a project. I hope it could help somebody in their projects and/or to solve the issue.

`redux: ^4.0`
`redux-promise-middleware: ^6.1`
`redux-thunk: ^2.3`

`.../redux-thunk-promise.d.ts`
```ts
// https://github.com/pburtchaell/redux-promise-middleware/issues/253

import { Action } from 'redux';
import { AsyncAction as OrigAsyncAction } from 'redux-promise-middleware';
import { ThunkDispatch as OrigThunkDispatch } from 'redux-thunk';

// -----------------------------------
// redux-promise-middleware extension
// -----------------------------------

declare type AsyncFunction<R = any> = () => Promise<R>;
declare type AsyncPayload<R = any> =
  | Promise<R>
  | AsyncFunction<R>
  | {
      promise: Promise<R> | AsyncFunction<R>;
      data?: any;
    };

export declare interface AsyncAction<R> extends OrigAsyncAction {
  payload?: AsyncPayload<R>;
}

type AsyncActionResult<A> = A extends AsyncAction<infer R> ? R : never;

export type AsyncFulfilledAction<A extends AsyncAction, Type = string> = Omit<
  A,
  'type' | 'payload'
> & {
  type: Type;
  payload: AsyncActionResult<A>;
};

type FulfilledDispatchResult<A extends AsyncAction> = {
  action: AsyncFulfilledAction<A>;
  value: AsyncActionResult<A>;
};

// ----------------------
// redux-thunk extension
// ----------------------

export declare interface ThunkDispatch<S, E, A extends Action>
  extends OrigThunkDispatch<S, E, A> {
  <A extends AsyncAction>(asyncAction: A): Promise<FulfilledDispatchResult<A>>;
}

export declare type ThunkAction<R, S, E, A extends Action> = (
  dispatch: ThunkDispatch<S, E, A>,
  getState: () => S,
  extraArgument: E,
) => R;
```

Then I use overridden types:

```ts
// action types
import { AsyncAction, AsyncFulfilledAction } from '.../redux-thunk-promise';

export const FETCH = '.../FETCH';
export const FETCH_PENDING = '.../FETCH_PENDING';
export const FETCH_FULFILLED = '.../FETCH_FULFILLED';
export const FETCH_REJECTED = '.../FETCH_REJECTED';

export interface FetchAction extends AsyncAction<ApiResult> {
  type: typeof FETCH;
}

export type FetchFulfilledAction = AsyncFulfilledAction<
  FetchAction,
  typeof FETCH_FULFILLED
>;

export type FooAction = FetchAction | FetchFulfilledAction | ...;
```

```ts
// actions
import { ThunkAction } from '.../redux-thunk-promise';
import { AppState } from 'store/';
import { FETCH, FetchAction } from './types';

export const fetchFoo = (): ThunkAction<void, AppState, null, FetchAction> =>
  (dispatch, getState) => {
    if (...) {
        dispatch({
          type: FETCH,
          payload: api.list(), // `api.list` is `() => Promise<ApiResult>`
        }).then(({ value }) => {
          // value is ApiResult
        });
    }
  };
```

**Comment by apieceofbart** [comment]
@Vovan-VE  Thanks a lot for your work on this, solving my exact use case.
However I think even without the `redux-thunk` the current typings for `redux-promise-middleware` are wrong. For example, if you check out the [typescript example](https://github.com/pburtchaell/redux-promise-middleware/blob/b8e4b0ac33efa726303738576da16c652cc8950e/examples/using-typescript/index.ts#L35) you could see that `store.dispatch(getDog())` does not return promise as it should.
