### ISSUE TITLE
Typescript Promise not work with AsyncAction

### ISSUE THREAD

**Issue by wulucxy** [pburtchaell/redux-promise-middleware#255]
```
// AsyncAction
export const queryBPI = (params: BPIParams): AsyncAction => {
  return {
    type: BitcoinActionTypes.BITCOIN_QUERY_LIST,
    payload: axios.get("someUrl"),
    meta: params
  };
};

// types
export type QueryBPI = typeof queryBPI;
```

the Result: 

![image](https://user-images.githubusercontent.com/5326403/62178702-96460a80-b37c-11e9-9a55-8e01886d9122.png)

the error message shows: `AsyncAction missing properties: then, catch`

So，how can I fix this？

---

- redux: 4.0.1
- redux-promise-middleware: 6.1.1
- react-redux: 6.0.1

**Comment by Vovan-VE** [comment]
`dispatch(asyncAction)` is a Promise - not an action itself.

**Comment by wulucxy** [comment]
I'am newer to typescript, so  how about the solution?

**Comment by nratter** [comment]
Would be nice for a solution to be documented here
