### ISSUE TITLE
A question about the middleware's return value

### ISSUE THREAD

**Issue by gezichenshan** [pburtchaell/redux-promise-middleware#259]
If a middleware comes before `redux-promise-middleware` and its return value is not `next(action)` but just like `return 'It is just a string'`. In this way, this final dispatch result will be 'It is just a string' not `promise.then(handleFulfill, handleReject);` returned by this lib. In this way the thenable ability of `redux-promise-middleware` will be disbaled.

I mean, If we want the result of dispatch to be thenable, which is enabled by this library, we should put it before the middlewares that don't return `next(action)`.

Am I right?

**Comment by pburtchaell** [comment]
Hi @gezichenshan, that's correct. The middleware in your stack will effect what is ultimately returned by the action creator. If the last middleware in your stack returns a string, then the action creator returns a string. If you want the action creatoers to return a promise, then Redux Promise Middleware should be the last in your stack of middlewares.

**Comment by gezichenshan** [comment]
@pburtchaell, yeah it is. Thanks !
