### ISSUE TITLE
Is this the same as acdlite/redux-promise?

### ISSUE THREAD

**Issue by Kronuz** [pburtchaell/redux-promise-middleware#27]
What is the difference between the two projects? it should be explained somewhere in the documentation, it's confusing... are both the same?

**Comment by marcelbuesing** [comment]
From what I can tell so far the major difference is, that
acdlite/redux-promise does not fire a "pending". You must manually handle that. E.g. when retrieving data you are only "notified" once the action is successful or fails.
Besides that mostly naming differences.

**Comment by Kronuz** [comment]
I understand. Maybe the README should mention this in a sentence. For some time I thought I needed redux-promise to use redux-promise-middleware

**Comment by pburtchaell** [comment]
I have never used [acdlite/redux-promise](https://github.com/acdlite/redux-promise), but, yes, I would say the major difference is that this middleware dispatches a PENDING action. This PENDING action allows for optimistic updates, which is something acdlite/redux-promise has not yet implemented. I would also argue the API for this middleware is more transparent and easier to integrate, e.g., you do not need to use [redux-actions](https://github.com/acdlite/redux-actions).

I'll update the README with the differences. Thanks for bringing this up.

**Comment by icflorescu** [comment]
A year later, another difference became apparent, and for the benefit of community, someone should mention it. This project is **actively maintained**, while [acdlite/redux-promise](https://github.com/acdlite/redux-promise) is not, judging by the number and age of unaddressed issues and PRs.
