### ISSUE TITLE
old state sent to components

### ISSUE THREAD

**Issue by ir-fuel** [pburtchaell/redux-promise-middleware#28]
First, I don't know if it belongs to this project, but since this only happens in async operations I think it might. If this does not belong here please tell me where I can get help.

The issue:
I save the user's profile using an ajax call to my server. To do that I use a promise action called `SAVE_PERSONAL_SETTINGS`, and process the states in my reducer (in my code `BEGIN` `SUCCESS` `ERROR`).
In order to update my gui, I update the state in the `BEGIN` call so the new values are present (optimistic update) and shown on screen. And this is where stuff goes wrong. To make sure that my async code correctly updates the gui I added a 5 second delay to my server before sending back the response, so I can see what is going on, and this is what happens.

In my example I am changing the distance unit from `mile` to `km`. So the initial state in `user.profile.personalInfo.distanceUnit` is `mile`.

The reducer gets executed with `_BEGIN`, I update the state so `user.profile.personalInfo.distanceUnit` is now `km`. In the mean time the ajax request is running. The logs clearly show that `next state` contains `km`, however my components receive new state containing `mile`. As long as the ajax request is running nothing changes (so I basically see my old value pop up in my GUI again). As soon as the ajax request finishes loading all of the sudden my component again gets new state and gets the correct values. Mind you that in the `_SUCCESS` code in my reducer I do not touch that state again, as it was already set in `_BEGIN`.

Here is a screenshot of the logs

![screen shot 2015-11-23 at 00 22 47](https://cloud.githubusercontent.com/assets/1573715/11327010/7bbc1390-9179-11e5-904c-9660c4b32587.png)

as you can see `next state` contains `user.profile.personalInfo.distanceUnit` = `km`

the next log is the log of the `user.profile.personalInfo` prop that gets set in my component, containing 'mile'.

the next log is the log of the `user.profile.personalInfo` prop that gets set in my component when the ajax request completes (5 seconds later), before logging `SAVE_PERSONAL_SETTINGS_SUCCESS`, containing 'km'.

I have no idea what is going on here. Maybe someone can help me out on how to debug this?

**Comment by tomatau** [comment]
please share the action creators that dispatch these states and the reducer methods that handle them.

**Comment by ir-fuel** [comment]
so we have
```
export function createPromiseAction(type, promise, metaData = {}, promiseTypeSuffixes = ['BEGIN','SUCCESS','ERROR']) {
  return {
    type,
    payload: {promise},
    meta: {promiseTypeSuffixes, metaData}
  }
}
```

and

```
export function saveUserPersonalSettings(settings) {
  return createPromiseAction(SAVE_PERSONAL_SETTINGS,savePersonalSettings(settings),settings)
}
```

`savePersonalSettings` does the networking call (using axios):

```
export function savePersonalSettings(settings) {
  return updateUser({personalInfo:settings})
}

function updateUser(values) {
  return postData('User/Update.php',values).then(function(result){
    return Promise.resolve(result)
  }).catch(function(result){
    console.log(result)
    if (result.status == 400) {
      const errorField = result.data.error.field
      const errorText = result.data.error.message

      return Promise.reject({errorText, errorField})
    } else {
      return Promise.reject({errorText:"Something went wrong"})
    }
  })
}


export function postData(path,obj,isSave=true) {

  return axios.post(BaseUrl+path,obj).then(function(response) {

    if(isSave)
      networkEventEmitter.emit(successEvent)

    return Promise.resolve(response)
  }).catch(function(response) {

    if(isSave)
      networkEventEmitter.emit(failureEvent)

    return Promise.reject(response)
  })
}
```


and then there is the reducer

```
let tempStorage = {}

export function reduceUsers(state = null, action = null) {
  let nextState = new StateUser()

  if(state)
    nextState = state

  let user = nextState.user
  let guiInfo = nextState.guiInfo

  const args = actionArguments(action)

  switch(actionType(action)) {
    case `${SAVE_PERSONAL_SETTINGS}_BEGIN`:
      const metaData = actionMetaData(action)
      tempStorage = user.profile.personalInfo
      const personalInfo = user.profile.personalInfo.merge(metaData)
      user = user.setIn(['profile','personalInfo'],personalInfo)
      guiInfo = guiInfo.set('isLoading',true)
      break
    case `${SAVE_PERSONAL_SETTINGS}_ERROR`:
      user = user.setIn(['profile','personalInfo'],tempStorage)
    case `${SAVE_PERSONAL_SETTINGS}_SUCCESS`:
      guiInfo = guiInfo.set('isLoading',false)
      break

  }

  nextState = nextState.set('guiInfo',guiInfo)
  nextState = nextState.set('user',user)
  return nextState
}

```


I hope this is a bit clear :)

**Comment by tomatau** [comment]
So there are three logs responding to the first action dispatch completion that we can see. The first log looks to be logging the previous state/props (with mile) and the next 2 are logging the state/props updated by the optimistic action update (containing mile).

Not sure I understand the problem.

**Comment by ir-fuel** [comment]
The log you see after `next state` is what is generated by the logging system after the reducer has ran on `SAVE_PERSONAL_SETTINGS_BEGIN`. 
I added a log myself inside my React component to see which state it receives (thats the next line, starting with `Object`). As you can see there the `distanceUnit` value does not correspond to the `distanceUnit` value in the `personalInfo` Object in the `next state` log.

5 seconds later (when the ajax request returns from the server) my component logger logs the next `Object` line, which does contain the correct state. As you can see, no `action` or `next state` logs have been printed in the mean time, so nothing has passed through the reducer between those 2 logs. 

So for some weird reason I get new state out of the reducer, the component receives the old state and only when the ajax request completes does the component get the new state (before passing through the reducer again with the `_SUCCESS` action).

Hope this is clear now.

**Comment by ir-fuel** [comment]
the main issue is that there is a 5 second delay between the first `Object` and the second `Object` log. These 5 seconds are the response time of my server (because I added a delay to make sure the processing state is correctly shown in the client). If my server were to take 10 seconds to process the request the delay would be 10 seconds. The issue is that during this time my ui actually shows the old values, and not the new ones I put in the state in the reducer.

**Comment by tomatau** [comment]
I'm familiar with the log monitor middleware. It will run before the state update reaches the component if it's configured correctly.

If you are updating the actual state object in your reducer and not creating a new one, the component will not receive a state update and that could explain why it's logging the wrong state... Hard to know this is the problem without seeing what is responsible for logging those objects.

The next 2 object logs have the correct state and are before the success action... this would lead me to assume that the state from the reducer IS coming through fine and the problem is in the component itself... maybe a parent reacting to state change and re-rendering the child (which logs) before the child responds to the appropriate state update.

try changing
```
  if(state)
    nextState = state
```

to
```
  if(state)
    nextState = { ...state }

or

  if(state)
    nextState = Object.assign({}, state)
```

The problem you're listing isn't with this middleware.

**Comment by ir-fuel** [comment]
I am using Immutable.js, so assignments are not a problem.

**Comment by ir-fuel** [comment]
I'll do some more investigation and come back to this when I have news.

**Comment by ir-fuel** [comment]
Found the issue. parameter called `props` and usage of `this.props` somewhere in a child component's code.

Whoops :/
