### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by pburtchaell** [pburtchaell/redux-promise-middleware#33]
It would be good to add examples; sometimes seeing actual code is better than reading the README.

- [x] Simple example without React
- [x] A README with some concise explanations of action creators you could use
- [ ] Example should demonstrate:
  - [ ] use the meta prop for more than just suffix configuration
  - [x] Combining redux-promise-middleware with redux-thunk
  - [ ]  How to change routes with React Router when a promise is fulfilled

**EDIT**: With the release of version 3.0.0, there is a simple and complex example of how to use the middleware. The simple example works, but the complex example is not finished. Help is wanted!

**Comment by tomatau** [comment]
Sounds good! It could be good to add examples for more core functionality like:

- global custom promiseSuffixTypes
- action specific ones
- data option for optimistic updates
- sharing meta between different actions

I think tests would also really help document this too.

Also, I think we should remove the /examples from the npm dist and keep that as minimal as possible.

I would work on some of this now, but I'm in the middle of a house and job move. Might have some time in 2 weeks from now.

**Comment by pburtchaell** [comment]
Great. Totally agree with the list and removing examples from npm dist. I thought I had already done that. :blush:

**Comment by alancasagrande** [comment]
:+1: for "How to use dispatch and getState in Promise.resolve" :)

```javascript
return { type: 'COOL_ACTION', payload: { promise: asyncCall().then( What goes here? ) } };
```

**Comment by pburtchaell** [comment]
You could use redux-thunk + redux-promise-middleware:

For example, here is an action that creates a new user then creates a session.

```
export function create(data) {
  return (dispatch, getState) => {

    return dispatch({
      type: types.CREATE_USER,
      payload: {
        promise: utils.create(data)
      }
    }).then(
       response => {
        dispatch(session.create({
          username: data.username,
          password: data.password
        }))
      }
    );
  };
}```

**Comment by tomatau** [comment]
```
return { type: 'COOL_ACTION', payload: { promise: asyncCall()
.then( (action, dispatch, getState) => {
 dispatch({ ...action, payload: [] })
 dispatch(anotherAction(getState().foo))
} ) }
```

**Comment by alancasagrande** [comment]
Thanks, that worked!

**Comment by jgoux** [comment]
Hello, is there a way / an example to write a reducer with helpers based on the three steps (pending, fulfilled and rejected) ?
A bit like [redux-actions `handleAction`](https://github.com/acdlite/redux-actions#handleactiontype-reducer--reducermap) with its `next` and `throw` key.

**Comment by tomatau** [comment]
I use handleActions with redux-promise-middleware.

Unfortunately I don't have a comprehensive example but I'll be working on some in the coming weeks if I get time.

Here's a C&P from a project I've been working with:

```js
export default handleActions({

  [ `${GET_TOPIC}_PENDING` ]: (state, action) => ({
    ...state,
    error: null,
    isPending: true,
    topic: initialState.topic
  }),

  [ `${GET_TOPIC}_REJECTED` ]: {
    throw: (state, action) => ({
      ...state,,
      isPending: false,
      error: action.payload.message
    })
  },

  [ `${GET_TOPIC}_FULFILLED` ]: (state, action) => ({
    ...state,
    isPending: false,
    topic: action.payload.topic
  }),
```

**Comment by pburtchaell** [comment]
> Is there a way / an example to write a reducer with helpers based on the three steps

I haven't discovered the best way to do this, but it is certainly something I have been thinking about. Let me poke around at some solutions when I can find some time. I created an issue for this at #35.

**Comment by baronnoraz** [comment]
I realize the example is a work in progress, but I was wondering if someone could elaborate on how the getAllPosts() function in /actions/post.js is supposed to end up flowing through the reducer, /reducers/posts.js.

When getAllPosts is called, I can see the service method get called and data successfully returned, but that's where it ends.  I was expecting the promiseMiddleware to somehow know that GET_POSTS was called and immediately call the GET_POSTS_PENDING, and then call GET_POSTS_FULFILLED when the data was returned, but nothing gets in the reducer. (I know it's wired up, because I see general Redux actions flow through it).

My apologies. I'm pretty new to React in general but was excited to find this library as it appeared to most closely match what was in my head.  I've had zero luck finding a full example showing how the view is rendered, an API call is made, the store is updated, and the view is updated.  Any help is immensely appreciated.

**Comment by tomatau** [comment]
You need to pass the return value from the action creator `getAllPosts` into a store.dispatch call. As long as promise middleware is wired up and the action created has a `payload.promise`, it will go through the _PENDING -> _FULFILLED steps.

**Comment by baronnoraz** [comment]
I'm using connect from react-redux... Perhaps I've misunderstood the purpose of mapDispatchToProps.  I thought that was binding my action creator to the store's dispatch.   Or maybe I'm invoking it wrong or shouldn't be invoking it in componentDidMount.

It's embarrassing to be this lost.  My apologies for cluttering this thread, but I do appreciate the help. 

```javascript
function mapStateToProps(state) {
    return {posts: state.data};
}
function mapDispatchToProps(dispatch) {
    return bindActionCreators({getAllPosts}, dispatch);
}

@connect(mapStateToProps, mapDispatchToProps)
export default class HomePage extends Component {

    componentDidMount() {
        getAllPosts();
    }
......
```

**Comment by tomatau** [comment]
I personally tend to find explicit dispatch calls easier to work with

```js
@connect(mapStateToProps)
export default class HomePage extends Component {
    componentDidMount() {
        this.props.dispatch(getAllPosts());
    }
```

**Comment by baronnoraz** [comment]
Thanks @tomatau.  That helped me identify that dispatch is not getting passed down into my HomePage component, so my problem must be upstream.  Thanks!!

**Comment by FoxxMD** [comment]
Just wanted to add my $0.02 -- the problem I faced in #53 is obvious in hindsight, but having not read the FSA docs too closely I was at a loss. I think it would be good to include an example that uses the `meta` prop for more than just suffix configuration (similarly to the way I needed to use it).

**Comment by pburtchaell** [comment]
@FoxxMD Agreed! I'll add that to the list.

**Comment by mauron85** [comment]
Probably nothing new, but this is example of how to redirect to another page after some ajax action completed with react-router.

myAjaxActionCreator.js
``` javascript
import * as api from '../api/api';
import { ACTION_FETCH } from '../actionTypes'
import { routeActions } from 'react-router-redux'

function fetch (id) {
  return {
    type: ACTION_FETCH,
    payload: {
      promise: api.find(id)
      .then( response => (action, dispatch, getState) => {
        dispatch({ ...action, payload: response.data });
        dispatch(routeActions.push('/')); // do redirect to desired page after ajax completed
      })
    }
  };
}

export function load (id) {
  return (dispatch, getState) => {
    // you can do check here if we have already cached object in state atom, so
    // we can skip server call and use cached object instead.
    return dispatch(fetch(id));
  };
}

```

**Comment by pburtchaell** [comment]
Hi all—I have added some initial code examples (the app runs, but there isn't much integration of Redux and async actions yet) on the v3 branch: https://github.com/pburtchaell/redux-promise-middleware/tree/v3/example.

**Comment by vaibhav-systango** [comment]
@pburtchaell Hi can you help me to use react-router-redux push here. It's not working
