### ISSUE TITLE
async/await syntax

### ISSUE THREAD

**Issue by jgoux** [pburtchaell/redux-promise-middleware#34]
Hello,
I want to use ES7's `async/await` syntax with the middleware, but oddly I can't make it works.

Here is the syntax I use : 
```js
export default function fetchPrelevements(jour) {

    return {

        type: "FETCH_PRELEVEMENTS",

        payload: {

            promise: async function () {

                const { data } = await axios.get("/api/prelevements", {
                    params: { debut: jour, fin: jour }
                })

                return data

            }

            // This syntax works :
            //promise: axios.get("/api/prelevements", {
            //    params: { debut: jour, fin: jour }
            //}).then(({ data }) => data)

        }

    }

}
```

The action is dispatched in the two cases, but with the async/await syntax it dispatches the function without being treated by the middleware, so without any suffixes.

Any idea ? :)

**Comment by tomatau** [comment]
you need to invoke the async function

**Comment by jgoux** [comment]
@tomatau lol, good catch !
Thanks for your quick answer. ;)
