### ISSUE TITLE
Reduce boilerplate for reducers used with async actions

### ISSUE THREAD

**Issue by pburtchaell** [pburtchaell/redux-promise-middleware#35]
When you have a reducer that is used with async actions, there is often a lot of boilerplate code that is required. For example, most of my reducers I use async actions with have a switch very similar to this:

````js
const defaultState = {
  isPending: undefined,
  isFulfilled: undefined,
  isRejected: undefined
}

switch (action.type) {
    case `${type}_PENDING`:
      return {
        ...state,
        ...defaultState,
        isPending: true
      };

    case `${type}_FULFILLED`:
      return {
        ...state,
        ...defaultState,
        isFulfilled: true,
        isSignedIn: true,
        token: action.payload
      };

    case `${type}_REJECTED`:
      return {
        ...state,
        ...defaultState,
        isRejected: true,
        error: action.payload
      };
   
   default: return state;
}
```

It would be nice to DRY up reducers that handle async actions and create a helper utility to do so.

Related to a comment on #33.

**Comment by pburtchaell** [comment]
I don't have a solution for this right now. My initial thoughts are to have a `createReducer` function that takes an `initialState` and the action type(s) for the reducer.

**Comment by aikoven** [comment]
Here's how I do it:

```js
import {ASYNC_ACTION, SYNC_ACTION} from './actions';

const reducer = handleActions({
  [ASYNC_ACTION]: {
    FULFILLED: (state, action) => ...,
    REJECTED: (state, action) => ...
  },
  [SYNC_ACTION]: (state, action) => ...
});
```

`handleActions` is similar to one from [redux-actions](https://github.com/acdlite/redux-actions), except that it first flattens object by concatenating keys via `'_'`, so it becomes:
```js
{
    ASYNC_ACTION_FULFILLED: (state, action) => ...,
    ASYNC_ACTION_REJECTED: (state, action) => ...,
    SYNC_ACTION: (state, action) => ...
}
```

**Comment by tomatau** [comment]
That API looks quite simple and effective. I'm guessing you still need to wrap the _REJECTED in a `throw` ?

**Comment by pburtchaell** [comment]
I like that approach.

Question related to this: do we we actually provide a `handleAction` function in the package that can be imported _or_ do we just include a basic example of what a `handleAction` function would look like in the documentation? I think just including it in the documentation would be fine.

**Comment by tomatau** [comment]
@aikoven have you made a PR adding this functionality to handleAction? I can imagine it being useful for multiple libraries.

@pburtchaell I think it makes sense to keep this project as small as possible, especially as redux-action already exists and works quite well, even without the extension that aikoven has suggested. So +1 for just documentation -- although, it would be nice to somehow offer that exact functionality.

**Comment by aikoven** [comment]
@tomatau I didn't do any PRs for the same reason — I think it's enough to have it noted in documentation as an example. Actually, I'm not completely sure that `handleAction` should be included in   *redux-actions* as well, because it is too easy to implement and also it may not be fit for some projects e.g. that use some custom middleware.

**Comment by tomatau** [comment]
@aikoven could you publish your own handleAction lib with this functionality you've described? I'd be happy to add it as an example when working with redux-promise-middleware.

**Comment by pburtchaell** [comment]
Agree with @tomatau—let us know if you want to make a lib @aikoven. Otherwise, I can put something together next week.

**Comment by aikoven** [comment]
@tomatau @pburtchaell here you go:

```js
function handleActions(reducerMap, initialState) {
  const flatMap = {};

  for (let actionType of Object.keys(reducerMap)) {
    let value = reducerMap[actionType];
    if (typeof value === 'object') {
      for (let suffix of Object.keys(value)) {
        flatMap[`${actionType}_${suffix}`] = value[suffix];
      }
    } else {
      flatMap[actionType] = value;
    }
  }
  
  return (state=initialState, action) => {
    const reducer = flatMap[action.type];
    return reducer ? reducer(state, action) : state
  };
}
```

**Comment by FoxxMD** [comment]
@aikoven How would you combine multiple `handleActions`? I want to write a function that handles actions from [redux-promise-middleware](https://github.com/pburtchaell/redux-promise-middleware) in a standard way and the combine those into one reducer.

Something like

```javascript
export function standardApiAction(type, initialState) {
  return handleActions({
    [type]: {
      FULFILLED: (state, action) => {
        return {
          ...state,
          loaded: true,
          loading: false,
          response: action.payload
        };
      },
      PENDING: (state, action) => {
        return {
          ...state,
          loaded: false,
          loading: true
        };
      },
      REJECTED: (state, action) => {
        return {
          ...state,
          loaded: true,
          loading: false,
          response: action.payload
        };
      }
    }
  }, initialState);
}
```

and then `combineReducer({standardApiAction(LOAD_X, state.x),...})`

**Comment by tomatau** [comment]
@aikoven do you have any tests for this?

**Comment by aikoven** [comment]
@FoxxMD not sure what do you mean by combining. One `handleActions` should be used to create a single reducer that handles specific part of your state tree. You can combine it with reducers for other parts using redux's built-in `combineReducers`. This might be relevant: https://github.com/rackt/redux/issues/749

@tomatau nope, sorry.

**Comment by tikotzky** [comment]
@tomatau @aikoven 
here are some basic tests for the `handleActions` function.

```js
import { expect } from 'chai';
import handleActions from '.....';

const ASYNC_ACTION = 'ASYNC_ACTION';
const SYNC_ACTION = 'SYNC_ACTION';

const reducer = handleActions({
  [ASYNC_ACTION]: {
    FULFILLED: (state, action) => ({...state, fulfilled: action.payload}),
    REJECTED: (state, action) => ({...state, rejected: action.payload}),
  },
  [SYNC_ACTION]: (state, action) => ({...state, sync: action.payload}),
});

describe('handleAction', () => {
  it('should run the FULFILLED reducer', () => {
    const action = {
      type: `${ASYNC_ACTION}_FULFILLED`,
      payload: 'fulfill me',
    };
    const state = reducer({}, action);
    expect(state).to.eql({ fulfilled: 'fulfill me' });
  });

  it('should run the REJECTED reducer', () => {
    const action = {
      type: `${ASYNC_ACTION}_REJECTED`,
      payload: 'i was rejected',
    };
    const state = reducer({}, action);
    expect(state).to.eql({ rejected: 'i was rejected' });
  });

  it('should run the SYNC reducer', () => {
    const action = {
      type: SYNC_ACTION,
      payload: 'i am sync',
    };
    const state = reducer({}, action);
    expect(state).to.eql({ sync: 'i am sync' });
  });
});
```

**Comment by tomatau** [comment]
@tikotzky and @aikoven I've used some of each of your suggestions for the described API to publish https://github.com/tomatau/type-to-reducer

**Comment by pburtchaell** [comment]
I'm going to check this out this weekend @tomatau. Thanks for trying to find a good solution. :smile: Do you want to link to it in the docs and close this issue? Perhaps mention it is an experiment/beta and also link to the closed issue so people can reference the discussion.

**Comment by pburtchaell** [comment]
I am going to include this in the docs of the version 3.0.0 release.
