### ISSUE TITLE
2.2.4 broken

### ISSUE THREAD

**Issue by steida** [pburtchaell/redux-promise-middleware#37]
While 2.2.3 works. Test case is Este code https://github.com/este/este/issues/633
Just try login, or check the code https://github.com/este/este/blob/master/src/common/auth/actions.js#L32

**Comment by pburtchaell** [comment]
@tomatau Are you available to look into this? I'm out of the pocket for the rest of this week.

**Comment by tomatau** [comment]
Yep, problems on both sides of this, I'll be making a PR soon so that we comply more accurately with the redux store.dispatch docs. Just need to think about handling our multiple dispatch calls from one original dispatch.

**Comment by steida** [comment]
I would love to help you with PR and tests! Since code becoming to look a bit messy. But time :(

**Comment by pburtchaell** [comment]
Alright, this should be fixed in version 2.3.0. Closing.
