### ISSUE TITLE
Return action object or promise

### ISSUE THREAD

**Issue by pburtchaell** [pburtchaell/redux-promise-middleware#39]
With the release of version 2.3.0, there has been some discussion at https://github.com/este/este/issues/633 regarding what the middleware should return. The two sides of this discussion are:

1. Return the action object
2. Return the promise object

If the action object is returned, as it is currently implemented by @tomatau via #38, accessing the promise would look like: 

```js
const action = store.dispatch(asyncRequest())
action.promise.then(...)
```

The current implementation follows the `dispatch()` API described by the [Redux documentation](http://redux.js.org/docs/api/Store.html#dispatch). The documentation specifies that it should return "the dispatched action".

The alternative would return the promise. For example:

```js
store.dispatch(asyncRequest()).then(...)
```

This implementation would not follow the API as it is described by the Redux docs, but it could be more convenient, as some have argued. I am happy with the current implementation, but if we want to continue a discussion about changing it I would be open to that as well.

**Comment by tomatau** [comment]
I've made a PR to the redux docs https://github.com/rackt/redux/pull/1103

I feel our current implementation would support more use cases than any other. It gives the original action passed in to the middleware-chain, before the action is used to create a _PENDING action.

This way a user can:
- access the promise that will resolve to the final action
- access the original action's type, meta and data properties

Option 2, returning a promise, you lose information about the original action.

Option 1, returning the second dispatched action - not sure how this would work, it can't be synchronously accessed as a return value?

**Comment by pburtchaell** [comment]
> Option 1, returning the second dispatched action - not sure how this would work, it can't be synchronously accessed as a return value?

Sorry, I meant option #1 would return the action. I've edited my original comment now.

**Comment by tomatau** [comment]
FWIW: I've been commenting on the redux PR and they say it's fine to return pretty much anything...

Maybe the most simple is to just return the promise like we did before I broke things.

**Comment by pburtchaell** [comment]
I think for right now it is okay to leave it as it is now. Let's see where the discussion on the Redux issue goes.
