### ISSUE TITLE
Allow optimistic updates

### ISSUE THREAD

**Issue by jarsbe** [pburtchaell/redux-promise-middleware#4]
Currently the payload is not returned in the PENDING action. This prevents optimistic updates. 

The payload is currently the promise. Instead the promise could be nested along side the initial data. 

```
{
    payload: {
        data: formData,
        promise: WebUtils.submitForm(formData)
    },
    types: ...
}
```

That way the action still adheres to FSA but allows for optimistic updates.

**Comment by pburtchaell** [comment]
Yes, this will be a good improvement to have! :+1: I am happy to add it, but I'm out on vacation until August 10 so I can get to it after then. However, if you would like it in the meantime, a PR is welcome.

**Comment by jarsbe** [comment]
Great, I'd love to write a PR, just wanted to run the idea past you first.

**Comment by wbecker** [comment]
+1. Came here looking to see if this was on the roadmap, would love to have this!

**Comment by pburtchaell** [comment]
`redux-promise-middleware@0.2.0` now includes support for optimistic updates. :100:
