### ISSUE TITLE
Best pattern for chaining dependent actions (Question)

### ISSUE THREAD

**Issue by baronnoraz** [pburtchaell/redux-promise-middleware#43]
react: 0.14.3
react-router: 1.0.0
react-redux: 4.0.0
redux: 3.0.4
redux-thunk: 1.0.0
redux-promise-middleware: 2.2.4

I have everything working together great, but I'm reaching a point in development where it would be beneficial to start chaining a series of actions together.  I know this has been covered in the README, #8, #24, and lots of other places, but I simply can't get any of them to work, so I must be going about it completely wrong.  

Here's an example use case:  
1. Create - creates a new record via async service call, store in {record: {}} state
2. Start - wait for the record to be created and then update the record in state to start a process
3. Redirect - redirect to a new page beginning the process

The Create and Start are individual actions that I'd like to use in a single new action if the user knows that they want to start the process when they create the record.

**actions.jsx**
```javascript
export function create(name) {
    return {
        type: CREATE,
        payload: {
            promise: axios.post(`${apiRoot}/create`, {name: name})
        }
    }
}

export function start() {
    return {
        type: START,
        payload: {
            promise: Promise.resolve()
        }
    }
}
```

**reducer.jsx**
```javascript
        case `${CREATE}_PENDING`:
        ...
        case `${CREATE}_SUCCESS`:
        ...
        case `${CREATE}_ERROR`:
        ...
        case `${START}_PENDING`:
        ...
        case `${START}_SUCCESS`:
        ...
        case `${START}_ERROR`:
```

Individually, both actions (action creators) do exactly what I want them to do.  However, I never seem to be able to get the second action to dispatch after the first one has finished.

I won't list all of the things I've tried, but here's an example of a failed attempt from #24.

```javascript
export function createAndStart(name) {

    return (dispatch) => {
        dispatch({
            type: CREATE_AND_START,
            payload: {
                promise: new Promise((resolve, reject) => {
                    dispatch(create(name))
                        .then(() => {
                            dispatch(start());
                        })
                        .then(() => {
                            dispatch(push('/start'));
                        })
                })
            }
        });
    };
}
```

In this example, I see the createInspection action dispatched.  I see it flow through each reducer state _PENDING then _SUCCESS, but I never see anything fall into the next .then()

I'm certain that I'm doing something stupid, but nothing has worked for me.  The example in the README fails for me initially because dispatch isn't the first argument I see, action is.  But even if I change that, the second action never gets dispatched.

**bad**
```javascript
Promise.resolve((dispatch, getState) =>
```

**good**
```javascript
Promise.resolve((action, dispatch, getState) =>
```

I appreciate any help that folks can offer.  Thank you!

**Comment by pburtchaell** [comment]
I'm busy for the rest of the week. I'll get back to you this weekend when I have some more time to read through your question to give you a worthwhile answer!

**Comment by baronnoraz** [comment]
Thanks!  Sorry to be a bother, I really want to learn the/a proper way to do things.  I'm grateful for the willingness to help.

**Comment by rkoberg** [comment]
I was looking for a way to do this type of thing as well. This works, but was wondering if there was a better way:
```
return ({fetch, settings: {firebaseUrl}}) => {
    return ({
      type: 'LOAD_PROFILE_USER',
      payload: {
        promise: fetch(`${firebaseUrl}/users/${slug}.json`)
          .then(response => response.json())
          .then(response => (users.viewer && users.viewer.slug === response.slug) ?
            Promise.resolve(loadProfileSettingsForm(response)) :
            Promise.resolve(true))
          .catch(err => {
            throw err;
          }),
      }
    });
  };
```

**Comment by rkoberg** [comment]
Also, if there is some way to do this with aysnc/await?

**Comment by tomatau** [comment]
Maybe this?

```js
export function createAndStart(name) {
  return (dispatch) => {
    dispatch({
      type: CREATE_AND_START,
      payload: {
        promise: new Promise(async (resolve, reject) => {
          await dispatch(create(name)).payload.promise
          await dispatch(start()).payload.promise
          dispatch(push('/start'))
        })
      }
    });
  };
}
```

Have a look at our tests to get more of an idea of the return from dispatch calls when using a promise-middleware-action

**Comment by baronnoraz** [comment]
@tomatau Thank you!!  That worked perfectly.   I truly appreciate the help, and I'll be sure to dig into the tests to learn more.

@rkoberg Hopefully this example using async/await helps you too...

**Comment by rkoberg** [comment]
Sure, but I just moved it to a separate async function (example below). Using Este, it takes care of dispatch for actions:
https://github.com/este/este/blob/master/src/common/configureStore.js#L23
https://github.com/este/este/blob/master/src/common/lib/injectDependencies.js

However, it just uses the dispatch function (not always a promise). What is the benefit of appending ```.payload.promise```? I want access to the data to transform for the reducer. And I am not clear what you are doing with ```resolve(push('/start'))```. What is that for?

Here is what I am doing:
```
async function _login(firebase, fields) {
  try {
    const authData = await firebase.authWithPassword(fields.toJS());
    const userData = await getUserFromAuthData(firebase, authData);
    return {authData, userData};
  } catch (err) { //eslint-disable-line brace-style
    throw err;
  }
}
```

**Comment by baronnoraz** [comment]
@rkoberg the `resolve(push('/start'))` bit was just for my specific example.  I needed to redirect upon completion of the second action.

**Comment by tomatau** [comment]
@rkoberg 
> What is the benefit of appending .payload.promise?

The return from dispatch is an action object with the promise available at `payload.promise`, this allows you to await for the promise to be resolved, following @baronnoraz question and code.

**Comment by rkoberg** [comment]
OK. I have setup the firebase functions to return a promise. ```authWithPassword``` resolves into ```authData``` first. Then, ```async getUserFromAuthData``` has an ```await``` inside of it (to another Promisified firebase function). It resolves and all the data is sent in the return to the reducer. In other words, I don't seem to need ```.payload.promise``` -- wondering if I am somehow doing something wrong that currently results in the correct result.

**Comment by tomatau** [comment]
The example I posted was using actionCreator functions inside an actionCreator and awaiting on dispatch calls, check the OP for the API of the functions used in the example code I posted.

**Comment by pburtchaell** [comment]
@rkoberg I am going to close this since we resolved the OP's question. Would you mind creating a new issue? I'm happy to help.

**Comment by rkoberg** [comment]
I think we are good.

**Comment by artemjackson** [comment]
One more example:
```
/*
 * redux-thunk + redux-promise-middleware + redux-actions
 */
const _createAndStart = createAction(CREATE_AND_START,
  async (name, { dispatch }) => {
    await dispatch(create(name));
    await dispatch(start());
    await dispatch(push('/start'));
  });

export const createAndStart = (name) =>
  (dispatch) => dispatch(_createAndStart(name, { dispatch }));
```
