### ISSUE TITLE
Issue with react-native

### ISSUE THREAD

**Issue by ayarulin** [pburtchaell/redux-promise-middleware#44]
[This notation](https://github.com/pburtchaell/redux-promise-middleware/blob/4c7078eae5c50c373b3e728e52a78a56706b0c01/src/index.js#L24) causes an error on react-native 0.14.2:

```js
    next({
        type: `${type}_${PENDING}`,
        ...!!data && { payload: data },
        ...!!meta && { meta }
      });
```
```
Error: In this environment the target of assign MUST be an object.This error is a performance optimization and not spec compliant.
```

rewriting with `Object.assign` solves issue:

```js
    next(Object.assign(
        {
          type: `${type}_${PENDING}`
        },
        ...!!data && { payload: data },
        ...!!meta && { meta }
      ));
```

**Comment by pburtchaell** [comment]
I have little experience with React Native. I'd be open to just using `Object.assign`, but any idea what would cause this to fail? I wonder if it could be an issue with the spread operator polyfill that Babel uses?

**Comment by pburtchaell** [comment]
@ayarulin I pushed a fix to https://github.com/pburtchaell/redux-promise-middleware/tree/react-native-fix.  Can you let me know if that works for you? If it does, I will merge and release.

**Comment by ayarulin** [comment]
sorry for delay, I've tested both fix-react-native and master branch, and don't see an error at all. Not sure what's going on, but seems like issue is not related to react-promise-middleware. Let's just leave all as is and keep eye on it
