### ISSUE TITLE
Doesn't work with React Native 0.17.0

### ISSUE THREAD

**Issue by Hxucaa** [pburtchaell/redux-promise-middleware#47]
As soon as running a project with this middleware on, a transform error is shown on simulator. It seems `.babelrc` file is the culprit.

**Comment by pburtchaell** [comment]
Ah. That file should not be included when you install the middleware via npm. I'll push up a fix shortly.

**Comment by pburtchaell** [comment]
Will you let me know if the release `redux-promise-middleware@2.3.2` works?

**Comment by steida** [comment]
Meanwhile this can be helpful. A gulptask for removing .babelrc files https://github.com/este/este/blob/72a8e68b2e47c1d6067c8d226d4425d18e7d0956/gulpfile.babel.js#L111

**Comment by Hxucaa** [comment]
The new version works now.

**Comment by pburtchaell** [comment]
Great!
