### ISSUE TITLE
Reducing boilerplate in reducers

### ISSUE THREAD

**Issue by tikotzky** [pburtchaell/redux-promise-middleware#48]
_This is really the same question as https://github.com/pburtchaell/redux-promise-middleware/issues/35, but that issue seems to have taken a different track._

It seems like pretty much everyone that is using `redux-promise-middleware` (or any other async middleware) is keeping the `promise` state in the redux store.

Stealing @pburtchaell example from #35, a typical reducer might look like.
```js
const defaultState = {
  isPending: undefined,
  isFulfilled: undefined,
  isRejected: undefined
}

switch (action.type) {
    case `${type}_PENDING`:
      return {
        ...state,
        ...defaultState,
        isPending: true
      };

    case `${type}_FULFILLED`:
      return {
        ...state,
        ...defaultState,
        isFulfilled: true,
        isSignedIn: true,
        token: action.payload
      };

    case `${type}_REJECTED`:
      return {
        ...state,
        ...defaultState,
        isRejected: true,
        error: action.payload
      };

   default: return state;
}
```

In the above example we are manually keeping `isPending`, `isFulfilled` and `isRejected` updated in state.

### Proposal

What I would like to propose is that instead of removing the `payload.promise` from the dispatched action, we replace it with an object that represents the promise state.

So for example if you dispatched an action that looked like this...
```js
{
  type: 'ADD_TODO',
  payload: {
    promise: somePromise,
    data: { id: 'some_id' }
  }
}
```

the actions that would get sent to the reducer would look something like...
```js
// PENDING action
{
  type: 'ADD_TODO_PENDING',
  payload: {
    promise: {
      isPending: true,
      isResolved: false,
      isRejected: false
    },
    data: { id: 'some_id' }
  }
}

// SUCCESS action
{
  type: 'ADD_TODO_SUCCESS',
  payload: {
    promise: {
      isPending: false,
      isResolved: true,
      isRejected: false,
      value: 'FOO' // <-- value from resolved promise
    },
    data: { id: 'some_id' }
  }
}

// ERROR action
{
  type: 'ADD_TODO_ERROR',
  payload: {
    promise: {
      isPending: false,
      isResolved: false,
      isRejected: true,
      value: 'ERROR' // <-- error from rejected promise
    },
    data: { id: 'some_id' }
  }
}
```

I'm not completely sold on the above action object shape or property names yet. But I wanted to put this out there to get feedback and see what others think about such an idea.

Thanks :smile:

**Comment by tomatau** [comment]
It would be quite simple to create a utility function for generating promises that resolve to the data structure you're suggesting. I don't think this sort of encouraged state structure is something that should be supplied by the middleware.

**Comment by tikotzky** [comment]
@tomatau thanks for your quick reply. 

While I understand that this middleware might not be the right place for this sort of state structure, I do disagree that you would be able to accomplish the same thing using a utility function.

The issue with using a utility function as demonstrated above is that you have to manage the `pending` state in the action creator while the `fulfilled` and `rejected` state get automatically  handled in the utility function. 

If you are manually managing the `pending` state in the action creator then you are almost back to using `redux-promise` which completely forces you to manually manage pending state.

That being said, what i'm really trying to figure out is the best way to track the promise state in redux so that your view can look something like the view below. If the best way is to use some sort of utility function then I'll be happy with that...

```js
const Component = ({ promise }) => (
  <div>
  	{ promise.isPending   ? <Spinner />  : null }
  	{ promise.isFulfilled ? <Success />  : null }
  	{ promise.isRejected  ? <ErrorMsg /> : null }
  </div>
)
```

**Comment by tomatau** [comment]
You can abstract further.

**Comment by tikotzky** [comment]
Yup and you can keep abstracting, in matter of fact you can actually abstract away the need for `redux-promise-middleware` and get away with just `redux-thunk`.

```js
const makeAction = ({ type, promise }) => {
  return dispatch => {

    dispatch({
      payload: {
        isPending: true,
        isResolved: false,
        isRejected: false,
      },
    });

    promise.then(result => {
      dispatch({
        payload: {
          isPending: false,
          isResolved: true,
          isRejected: false,
          value: result,
        },
      });
    });

    promise.catch(err => {
      dispatch({
        payload: {
          isPending: false,
          isResolved: false,
          isRejected: true,
          value: err,
        },
        error: true,
      });
    });

    return promise;
  };
}
```

All programming really is about is finding the right layer of abstraction :smile:

**Comment by YAndrew91** [comment]
Storing promise anywhere to read its state is incorrect idea itself IMO. Promises aren't state machines. I don't think it's possible to abstract anything in this issue, you cannot generally predict how state change of some action's promise should change state of a store. You only can write 3 reducers for each async action, where you define how store state should be changed.

**Comment by pburtchaell** [comment]
Just reading this issue for the first time—sorry, busy month. 

My opinion is including promise state proposed—in the action—would be problematic. First, you loose access to the original promise, which would prevent you from chaining multiple actions together via `then` or using `Promise.all()` to combine multiple actions. This functionality is key to async code. Secondly, you impose a state structure that everyone may not want to use. 

The desire behind #35 was to design a function that could help cut down the boilerplate in reducers that handle async actions. This function would likely not be a part of the middleware and would just be included in the docs as an example. I don't want to change the API for the middleware itself.

**Comment by tikotzky** [comment]
@pburtchaell thanks for taking time to review :smile:
