### ISSUE TITLE
Error Actions override payloads

### ISSUE THREAD

**Issue by SRachamim** [pburtchaell/redux-promise-middleware#49]
I want to pass my _ERROR action a payload (in addition to the Error object that overrides the payload. I can pass _START and _SUCCESS actions a payload with a data property, but I lose it on the _ERROR action.

**Comment by tomatau** [comment]
This should already be supported, can you share some code?

**Comment by SRachamim** [comment]
This is my action:

```
export const unSubscribeToExpert = person => {
  return () => ({
    type: UN_SUBSCRIBE_TO_EXPERT,
    payload: {
      promise: apiUnSubscribeToExpert(person.get('id')),
      data: {
        person // don't see it in reducer
      },
      person // don't see it in reducer
    },
    person // don't see it in reducer
  });
};
```

and this is the action I get in my reducer:
```
{type: "UN_SUBSCRIBE_TO_EXPERT_SUCCESS", payload: true}
```
or:
{type: "UN_SUBSCRIBE_TO_EXPERT_SUCCESS", payload: /*Error object*/}
```

**Comment by tomatau** [comment]
The data property is only for the optimistic update from a pending action. You should already have it in state for the success or rejected action reducer function.

If you want to override the fulfilled and rejected actions, you need to do that by what you resolve or reject in the promise.

Take a look at the tests.

**Comment by SRachamim** [comment]
The solution is what you suggested, to resolve it on action and modify the response, though I think it's better to not modify the action but to merge it:
```
{
...originalAction,
type: `${originalAction}_${_SUCCESS/ERROR/START}`,
payload: originalAction.payload
}
```
If you agree I can handle it.

**Comment by tomatau** [comment]
If you resolve a thunk, the first arg is the fulfilled/rejected action for you to use
