### ISSUE TITLE
should meta attribute be preserved ?

### ISSUE THREAD

**Issue by davidwatkins73** [pburtchaell/redux-promise-middleware#5]
Example use case:

Performing a deletion  (eg. DELETE /api/thing/23). 
The backend responds with a simple true/false indicating outcome of deletion. 

To update the store, I require the id (23) but it's not available through the FULFILLED action.  I believe setting a 'meta' attribute via the action creator should allow me to pick it up later, but it is being discarded in the subsequently dispatched actions.

**Comment by pburtchaell** [comment]
Yes, you are right it should be. I'll look into this after August 10—since I am out on vacation now, but if you'd like, a PR is welcome. This should be a pretty quick fix.

**Comment by pburtchaell** [comment]
This feature is released to npm as `redux-promise-middleware@0.2.1`. You may want to consider trying an optimistic update here instead of passing it within the meta attribute. We just added that feature. Checkout the README.
