### ISSUE TITLE
How to differentiate between the same action dispatched multiple times consecutively?

### ISSUE THREAD

**Issue by FoxxMD** [pburtchaell/redux-promise-middleware#53]
I've got an action creator `deleteItem()` that takes an array of ids. Inside the action I iterate through the array and dispatch an action with the type `DELETE_ITEM` and a promise making an api request (to `/api/item/${id}`).

Now, for the `PENDING` phase of this action-promise everything is perfect because I have also attached `data: id` to the dispatched action, so I can get that id from `action.payload` in the function that takes care of the pending phase. But for `FULFILLED` I no longer have that id and so I can't determine which id I need to remove from the state.

Initially I tried storing that id in the state during the pending phase but I quickly realized this isn't helpful since the requests are async.

Ideally, having that id as a prop (like `data`) in the `FULFILLED` phase would solve my problem, but I feel like there must be a reason it isn't included. I know the docs say it's for optimistic updates only, but why?

How should I be handling this scenario?

**Comment by tomatau** [comment]
You can add the id to the meta data for the action, it will be persisted for all action types.

**Comment by FoxxMD** [comment]
Ah! I had skimmed over that section in the [FSA](https://github.com/acdlite/flux-standard-action#meta) docs and it hadn't occurred to me I could use it like that. Thanks!
