### ISSUE TITLE
Question: Is passing additional data to the reducer via the `meta` property the intended way to do so?

### ISSUE THREAD

**Issue by ccnokes** [pburtchaell/redux-promise-middleware#56]
I was looking for a way to pass additional data in my actions to my reducer so that the it can decide if that action actually needs to be dispatched. For example, if a user attempts to load the same resource twice, I can turn that into a no-op in the reducer by comparing the previous id with the pending one. 

```javascript
// in a react component
actions.loadFilter(id);

// filterActions.js
export function loadFilter(id) {
    return {
        type: types.LOAD_FILTER,
        id: id, // <--- doesn't get passed in the LOAD_FILTER_PENDING action
        payload: {
            promise: filtersAPI.getFilter(id),
            id: id // <---  this neither
        },
        meta: {
           id: id // <--- this does work, however is this the intended behavior of the library?
        }
    };
}
//when the above is dispatched, this is the resulting action object:
// {type: "LOAD_FILTER_PENDING", meta: { id: 123 }}

// filtersReducer.js
        case types.LOAD_FILTER + '_PENDING':
            // if they request the same filter consecutively then it's a no-op
            let prevId = _.get(state, 'currentFilter.data.id');
            if(prevId && prevId === action.meta.id) {
                return state;
            }
            // ...other stuff removed for brevity...
```
This behavior doesn't seem to be documented so I thought I would ask if this is how the library was intended to be used and if doing this could cause breakage in the future. 

I'm new to redux and react, so sorry if I'm stupid about all this :smile:

**Comment by pburtchaell** [comment]
I hope this can clear it up for you: 
1. The `meta` property is from [flux standard action (FSA)](https://github.com/acdlite/flux-standard-action)
2. Your `id` is not included in the action because FSA only allows a `type`, `payload` and `meta`.
3. The `meta` property is optional and can be any value. As quoted from the standard: "It is intended for any extra information that is not part of the payload."

Let me know if you have any other questions.

**Comment by ccnokes** [comment]
Gotcha, that helps. Thanks!
