### ISSUE TITLE
Dispatch additional actions?

### ISSUE THREAD

**Issue by pburtchaell** [pburtchaell/redux-promise-middleware#57]
So I have been using the middleware in a project that has a spinner that shows whenever a network request is made (and hides when the request is fulfilled). This project also shows an error notification whenever a network request is rejected.

Instead of handling this on a request-by-request basis, I created a second middleware that looks at the `type` of the action and checks via regex if it is appended with one of the promise types. If it is, then an action is dispatched to tell me that a request is pending or rejected. 

For example, if you were to log the types (beware—this is very pseudo), it would look like this:

```
console.log(action.type) => 
GET_POSTS_PENDING
PENDING
GET_POSTS_FULFILLED
FULFILLED
```

Or, if rejected:

```
console.log(action.type) => 
GET_POSTS_PENDING
PENDING
GET_POSTS_REJECTED
REJECTED
```

I then have a reducer that handles the `PENDING`, `FULFILLED` and `REJECTED` actions. My spinner and error notification components are connected to this reducer.

My thought is this: why have a second middleware handle dispatching these actions? It could be moved into redux-promise-middleware and enabled via a configuration option. The types dispatched would just be the promise types used already, so that could be configured as well. For example:

```js
composeStoreWithMiddleware = applyMiddleware(
  promiseMiddleware({
   requests: true // dispatch additional request actions
  })
)(createStore);
```

Typically, I would prefer to keep the API of the project minimal, but I think this would be a benefit that many people could use. Spinners and errors are both pretty common UI elements lots of projects use. I'm wondering what the thoughts on this are. cc/ @tomatau

**Comment by tomatau** [comment]
I think I get the reasoning for this, although I haven't gone down this more 'global' path for managing errors or loading state for the app. I tend to keep to local state.

Personally, I think this API addition would be a little bit too unique to implementation details.  Many apps out there could be taking completely different approaches to tackle the same problem. Also, if I was coming fresh into a new project with `requests: true`, it wouldn't be super obvious that this was making the global loading spinner work correctly -- and visa versa.

So, I tend to favour more `compositional` approaches, such as the middleware you have described... or even, to be super explicit... having the regex match against action.type performed in a `globalState` reducer:

```js
const defaultState = { isError: false, isLoading: false };
const globalStateReducer = (state=defaultState, action) => {
   switch (true) {}
    case action.type.match(pending_regex):
      return { ...state, isLoading: true }
    case action.type.match(rejected_regex):
      return { ...state, isError: true }
    default:
      return state;
   }
}
```

I find this approach more explicit. Although, it requires some synchronisation between the different actionTypeSuffixes and the regex checks.

But overall, happy to let the wider community decide :)

**Comment by pburtchaell** [comment]
I think you make a good point. :100: I am going to revisit my implementation of this with your suggestion to move the regex into the reducer.
