### ISSUE TITLE
Middleware never ending loop when using with react-router-redux

### ISSUE THREAD

**Issue by mauron85** [pburtchaell/redux-promise-middleware#60]
Hi, it seems that using redux-promise-middleware together with react-router-redux ends up in never ending loop.

EDIT: I've made example to reproduce the issue - https://github.com/mauron85/react-promise-middleware-example. Run dev server. Visit localhost:3000 and watch how hash history changes without any interaction (due middleware loop).

**Comment by tomatau** [comment]
Strange, works for me on the setup I use here. https://github.com/tomatau/breko-hub/tree/master/src/app/state.

Only issue I have is that calling `listenForReplays(store)` triggers a double update on the page load. Remember that the devtools actually updates the store on a tick, so potentially wiring up the hash history might be confusing the react-router-redux to think that the current page isn't right.

I can't even think how the promise middleware would be interfering with this.

**Comment by mauron85** [comment]
@tomatau thanks for the lead. Removing ```listenForReplays``` stops doing redirections. Need to investigate what it's doing it at first place. Any suggestions?

**Comment by mauron85** [comment]
Found my problem (feeling bit ashamed of it :-))
I was applying middleware wrong:


```
const reduxRouterMiddleware = syncHistory(hashHistory);
applyMiddleware(thunk, promiseMiddleware, reduxRouterMiddleware)
```

but I should apply result of function call

```
const reduxRouterMiddleware = syncHistory(hashHistory);
applyMiddleware(thunk, promiseMiddleware(), reduxRouterMiddleware)
```

**Comment by tomatau** [comment]
Ooh yeh! Completely didn't spot that you were doing that -- glad to hear it's fixed.
