### ISSUE TITLE
Question - setup react-native with promise

### ISSUE THREAD

**Issue by ws3li** [pburtchaell/redux-promise-middleware#63]
Hi ,

I am trying to setup my react-native to use the redux promise middleware and using Fetch.
Here is the code below for my **actions** file:

```
return {
  type: GetData,
  payload: {
    promise: fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(data)
    })
    .then( function(response) {
      return response.json(); 
    })
    .then( function (json) {
      return json;
    })
  }
}
```

And in my **reducer**  file I do the following:
```
switch (action.type) {
    case GetData:
    return { ...state, data: payload }
    default:
    return state;
  }
```

I placed a **debugger** in my switch case reducer but I am not getting a response back.
However, if I instead have the following in my **actions** file (without the promise key):

```
return {
  type: GetData,
  payload: fetch(url, { ...same as above... })
}
```

I get a promise back in my **reducer**, but it does not contain any data.

Can anyone give me an example of using the redux promise along with react-native fetch?
Thank you in advance!

**Comment by ws3li** [comment]
I figure it out. The problem is with my reducer. 
I was previously using redux-promise and recently switched to this. I just review the example provided. and figure the difference.

**Comment by theaklair** [comment]
Hi.
Having kind of similar issue.
Could you explain how it worked for you? Would be great.
Trying to return promise as s "default" state in Redux reducer - promise returned, but as Promise object with { _45, _81, _65, _54 } keys O_o
However  object.["_65"] key contains items collection I need.
Using React Native and redux-promise.

`async function getTodoItemsArray(){

  var TodoItemsArray=[...]

  await AsyncStorage.setItem('TodoItemsArray', JSON.stringify(TodoItemsArray));

  items = await AsyncStorage.getItem('TodoItemsArray');

  items = JSON.parse(items);

  return items;
}


export default function reducerTodolist( state = getTodoItemsArray(), action ) {

  switch(action.type) {

    ...

    default: {

      return state;
      //state["_65"] contains real items I need...

    }

  }
}`

**Comment by pburtchaell** [comment]
@theaklair You should evaluate the type of the action. The [example](https://github.com/pburtchaell/redux-promise-middleware/blob/master/examples/complex/reducers/post.js#L3) should be useful for you.

**Comment by theaklair** [comment]
@pburtchaell Thanks!

**Comment by gerrold** [comment]
@pburtchaell the link you provided is 404.

**Comment by 2ducanhpham** [comment]
how to fix?
