### ISSUE TITLE
sequential async actions?

### ISSUE THREAD

**Issue by tony-garcia** [pburtchaell/redux-promise-middleware#64]
Hello,
First of all thanks for your work on this middleware.
I'm having some trouble following an example in the docs. I'm still somewhat of a newcomer to react/redux so please bear with me. Currently I have an action creator that returns a promise from a connect() function (essentially it's a login):

```js
export function connect(connectionParams) {
  return {
    type: CONNECT,
    payload: {
      promise: authUtil.connect(connectionParams),
    }
  };
}
```

This is working fine. But now I want to dispatch another async action when the connect() promise resolves successfully. In your docs you have 'Dispatching Actions when Promises are Resolved' which seems like exactly what I'm looking for. But in the example provided:

```js
const actionCreator = () => ({
  type: 'FIRST_ACTION_TYPE',
  payload: {
    promise: Promise.resolve({
      type: 'SECOND_ACTION_TYPE'
      payload: ...
    })
   }
});
```

I'm not clear where in this structure my connect() promise (corresponding to the FIRST_ACTION_TYPE) in this action creator) would go. Also would this still dispatch the _PENDING, and _FULFILLED/_REJECTED actions of the first action type?
Thanks.

**Comment by tony-garcia** [comment]
Whoops. Sorry. I noticed this subject has been touch upon in some closed issues. I'll go take a look at those and re-open this if I don't find anything that helps.

**Comment by tony-garcia** [comment]
OK, so using issue #24 as a guide here is the code I used to make this work:

```js
export function connect(connectionParams) {
  return {
    type: CONNECT,
    payload: {
      promise: new Promise((resolve, reject) => {
        authUtil.connect()
          .then(response => {
            resolve(response);
            dispatch(fireAnotherAction())  // this is the secondary action     
          })
          .catch(error => {
            reject(error);
          });
      })
    }
  };
}
```
Seems like this is behaving the way I want. The issue, though, is that this code is so different from the example code given in the docs (quoted in the original post). So I guess I'd like to ask --- is it just that the docs aren't 100% right am I still just not understanding something?
Thanks.

**Comment by pburtchaell** [comment]
You would want something like this:

```
export function connect(connectionParams) {
  return dispatch =>  {

    dispatch({
      type: CONNECT,
      payload: {
        promise: new Promise((resolve, reject) => {
          authUtil.connect()
            .then(resolve)
            .catch(reject);
        })
      }
    }).payload.promise.then(() => dispatch(fireAnotherAction()))
  };
}
```

**Comment by tony-garcia** [comment]
Ah I get it. So I was close at least. Thanks a lot!

**Comment by tony-garcia** [comment]
Hmmm.
Actually, when I tried out your code, the secondary action fired whether or not the first one resolved OR rejected.

**Comment by tomatau** [comment]
Try this. You can probably just not do the rejection handler
```js
export function connect(connectionParams) {
  return {
    type: CONNECT,
    payload: {
      promise: authUtil.connect(connectionParams)
        .then(
            // success, resolve a thunk
          (resolvedFromConnect) => (action, dispatch) => {
            // here you have access to a half complete action object
            // and your value resolved from authUtil.connect.
            // you can merge the two and pass into dispatch
            dispatch(Object.assign(action, resolvedFromConnect)) // or something?
            // now dispatch your second action
            dispatch(secondActionCreator())
          },
          // optionally supply a rejection handler too..
          // this can also be a thunk if you want
          (rejectedFromConnect) => (action, dispatch) => {
            // do whatever
          }
        )
    }
  };
}
```

**Comment by tony-garcia** [comment]
Cool, that worked. Thanks! In my case, instead of the passing the Object.assign() call to dispatch(), I did:

```js
action.payload = resolvedFromConnect
dispatch(action);
```
One thing I'm curious about is what exactly the 'double-fat-arrow' notation is doing where it's going.
```js
(resolvedFromConnect) => (action, dispatch) => {...
```
I've recently been learning using the ES2015 stuff and I'm familiar with the fat arrow function notation but this is a bit different.

**Comment by tomatau** [comment]
So it's a function that's returning another function.

It's effectively this:
```js
function(resolvedFromConnect) {
  return function(action, dispatch) {
  }.bind(this)
}.bind(this)
```
