### ISSUE TITLE
Best way to handle specific errors globally 

### ISSUE THREAD

**Issue by nmaves** [pburtchaell/redux-promise-middleware#69]
So we have a use case in our application where we would like to always dispatch a logout action when ever we get a 401 back from our API.  Likewise I would like to have a global error action dispatched for every 500> response that we get back.  

Is there a good way to do this with redux-promise-middleware?

I was thinking that we might be able to pass in configuration to the initializer where we could provide handlers for these specific cases.

**Comment by nmaves** [comment]
Well here is what I started with.  I added a config option called errorCallback(response).  Right before you reject the promise you call this callback.  At such point my callback can decipher what to do based on response.status.

**Comment by tomatau** [comment]
You can handle actions that match a regex of `/_REJECTED/` in your logout reducer. Which would be one shortcut. Another is make a reusable function that wraps around your promise calls and sends off the required error actions in the promise rejection case.

**Comment by pburtchaell** [comment]
Note: it would be good to add a guide on this in the docs. This isn't the first we have been asked something related to globally handling actions.

**Comment by pburtchaell** [comment]
@nmaves Have any questions?

**Comment by nmaves** [comment]
Nope I think both of the solutions here would work perfect.

**Comment by pburtchaell** [comment]
I added a guide for this: https://github.com/pburtchaell/redux-promise-middleware/blob/master/docs/guides/global-handling.md

**Comment by gubasso** [comment]
@pburtchaell , the guide link is broken. Is there anywhere else?

**Comment by pburtchaell** [comment]
@gubasso https://github.com/pburtchaell/redux-promise-middleware/blob/master/docs/guides/rejected-promises.md

**Comment by gubasso** [comment]
Thanks @pburtchaell !
