### ISSUE TITLE
Change reject reason to instance of Error

### ISSUE THREAD

**Issue by steida** [pburtchaell/redux-promise-middleware#70]
Because https://github.com/petkaantonov/bluebird/blob/master/docs/docs/warning-explanations.md#warning-a-promise-was-rejected-with-a-non-error

Of course, it's ok from JavaScript point of view. I had to disable this warning in https://github.com/este/este, because I can't ensure all third party libraries will follow this rule. Still, it's a good advice.
Quick fix:

```js
var error = new Error('fok');
error.reason = reason;
error.action = rejectedAction;
reject(error);
```

If you want to improve DX, use https://github.com/julien-f/js-make-error

**Comment by pburtchaell** [comment]
This makes sense. I can look into the changes, but could you make a JSBin or some quick example that demonstrates it? I understand the change, but having it in code would be nice.

**Comment by steida** [comment]
That's the only code I can provide you right now.

https://github.com/este/este/blob/master/src/common/lib/validation/ValidationError.js

**Comment by pburtchaell** [comment]
@steida I've opened [a PR](https://github.com/pburtchaell/redux-promise-middleware/pull/81) with the behavior I think you are requesting. The [argument is an instance of Error](https://github.com/pburtchaell/redux-promise-middleware/pull/81/commits/7ee396baf78326eb922958a1c2135c6cf9d2be8d#diff-faa503f61f8addeb603095cc2f40c82eR350). 

Does this resolve your issue?

**Comment by steida** [comment]
Yes, thank you.

**Comment by pburtchaell** [comment]
Great. I'm going to keep this open until I merge and release it.
