### ISSUE TITLE
Original promise can be returned to avoid anti-pattern

### ISSUE THREAD

**Issue by Willyham** [pburtchaell/redux-promise-middleware#71]
## Version
3.0.0
## Test Case
```
    it('propagates the original promise', async () => {
      const actionDispatched = store.dispatch({
        type: defaultPromiseAction.type,
        payload: Bluebird.resolve(promiseValue)
      });

      // Expect that the promise returned has bluebird functions available
      expect(actionDispatched.any).to.be.a('function');

      await actionDispatched.then(({ value, action }) => {
        expect(value).to.eql(promiseValue);
        expect(action).to.eql(fulfilledAction);
      });
    });
```
## Expected Behavior
The original promise should be chained and returned.

## Actual Behavior
A new native promise is created.

----
I can't see any reason for creating a new promise and rejecting/resolving it. This perpetuates the [deferred anti-pattern](https://github.com/petkaantonov/bluebird/wiki/Promise-anti-patterns#the-deferred-anti-pattern). When changing the code to return the original promise, all of the test suite continues to pass.

If there is a reason that a new promise must be created (and that's fine if there is), then the reason is not covered in the tests.

The code could be changed to:

```
      return promise.then(
        (value = null) => {
          const resolvedAction = getAction(value, false);
          dispatch(resolvedAction);
          return { value, action: resolvedAction };
        }).catch((reason = null) => {
          const rejectedAction = getAction(reason, true);
          dispatch(rejectedAction);
          const rejectedDetails = { reason, action: rejectedAction };
          throw rejectedDetails;
        });
```

to allow any promise library to continue working as expected.

Happy to submit a PR if this is a valid change.

**Comment by pburtchaell** [comment]
First, this middleware is designed to work with the [standard](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) `Promise` object prototype methods. this standard follows the [A+ spec](https://promisesaplus.com). The middleware is not designed to work with the Bluebird API. Is there a reason you are using the Bluebird library instead of the standard, which has a polyfill and is supported [in all browsers except IE](http://caniuse.com/#search=Promises)?

Second, there is a reason a new promise is created and it is covered in the tests. The anti-pattern you linked does not apply here. This reason a new promise is created is demonstrated in the [version 3.0.0 release notes](https://github.com/pburtchaell/redux-promise-middleware/releases).

When `then` is called on a settled promise (as it in the middleware), the `then` and `catch` methods on the returned promise object will have "unexpected" behavior. In order to preserve the expected behavior of `then` and `catch` a new promise must be created. See the release notes for an example.

**Comment by Willyham** [comment]
The point of the promises/A+ spec is that different implementations are interoperable, so if somebody chooses to use, for example, Bluebird (for extra functionality) they should work together nicely. I am using Bluebird on both the front and back end for various reasons, and needing to coerce these promises into that type is unnecessary.

I'm not sure I understand the reasoning behind the unexpected behaviour. When I made the change to return the existing promise rather than creating a new one, all tests passed. That leads me to believe that either a) the tests don't cover the issue with not creating a new promise or b) the previous implementation was incorrect.

I actually just checked the previous implementation (in 2.2.3) and it looks like it wasn't correct. I am happy to explain why that is and the difference between that and my implementation if you'd like :)

**Comment by pburtchaell** [comment]
Yes, I understand the point is for the implementations to be interoperable; it's in the description of the spec... Yes, the Bluebird API is an implementation of the A+ spec and is interoperable to an extent with the standard promise API, but it also adds a number of methods (such as the `.any()` method you included in your test example) not included in the spec. As I explained before, this middleware is designed to work with and tested for with the standard promise object implemented in browsers. I'd like to make it work with Blackboard if possible, but you can't expect it to.

I understand the differences between 2.x, 3.x and your implementations. Basic differences, where `promise` is the original promise object:

- 2.x implementation: `return promise.then(onFulfill, onReject)`
- 3.x implementation: `return new Promise((resolve, reject) => ...)`
- Proposed implementation: `return promise.then(...).catch(...)`

The problem with the 2.x implementation is once `then` is called on a rejected, settled promise, you loose the ability to call the `onReject` argument.

Yes, your proposed implementation would have the same results as the present 3.x implementation, while also preserving the API from whatever promise library you use, but throwing an exception in the middleware could be problematic, no? I have the following questions: 

- Would stack traces work as expected? Consider throwing an exception during an network request; one would want to be able to trace the error to its origin.
- Addtionally, JS will allow you to throw anything as an exception, but should you? Probably not. In my opinion, exceptions should always be an Error object.

Also wondering what @tomatau's opinion is here.

**Comment by Willyham** [comment]
I think the main issue with the 2.x was that the promise wasn't returned which mean't that you couldn't chain anything, but you raise some good questions about my proposal. 

The `throw` from within the reject will cause the returned promise to be rejected with that reason. You're only going to get the stack trace from the point of the `throw`, but I think that's as functionally useful as getting the stack trace from the point where the promise was created - I'll double check this.

I agree that it should be an error instance for the rejection (also mentioned here https://github.com/pburtchaell/redux-promise-middleware/issues/70). I think that that can be done whilst preserving backwards compatibility.

One more open question is whether it should be `return promise.then(onResolve, onReject)` or `return promise.then(onResolve).catch(onReject)`. I believe that the latter is more appropriate (following [this](https://github.com/petkaantonov/bluebird/wiki/Promise-anti-patterns#the-thensuccess-fail-anti-pattern) logic)

I will put a little bit more effort into this shortly and then we might be able to satisfy all of the concerns.

**Comment by tomatau** [comment]
What's the use case for resolving an object containing a value and promise? If the value is being dispatched it should already be available and in a more useful place.

**Comment by tomatau** [comment]
https://github.com/pburtchaell/redux-promise-middleware/issues/67#issuecomment-211599169

**Comment by Willyham** [comment]
@tomatau I like your solution, but why resolve the promise with the action (result of the dispatch function) even in the rejection case? That precludes me from writing a middleware which catches rejected promises.

Imagine this scenario; we have a store with 'redux-promise-middleware' and a store with a hypothetical -'api-error-logger-middleware'. That second middleware exists to log all API failures explicitly, without any need to inspect their type or any knowledge of the '_REJECTED' suffix:

``
const apiLoggerMiddleware = store => next => action => {
  const result = next(action);
  if (!isPromise(result)) {
    return result;
  }
  return result.catch(err => {
    // Do something with err
    // Maybe re-throw err
  });
}
```
With your change, I would have to call `.then` and inspect the promise's state (something not supported by es2015 implementation). In the current implementation, I can/should call catch here.

I feel like there's a little bit of a diversion from the original intent of this issue, anyway. What I would like to propose is to keep the exact same behaviour and API, but return the type of promise the user passed in rather than a new es2015 Promise. That can be achieved with the sample code that I added at the start of this issue.

Then we can discuss other additive or breaking changes separately.

**Comment by Willyham** [comment]
Sorry, one change I did make is to move to `.then(..).catch(...)`. Whilst I do think that makes more sense, it's a change in behaviour. I'm happy to start with `.then(resolved, rejected)` to maintain the current API.

**Comment by tomatau** [comment]
Hi @Willyham - I don't understand this

> but why resolve the promise with the action (result of the dispatch function) 

I'm not doing this?

**Comment by Willyham** [comment]
Check here: https://github.com/tomatau/redux-promise-middleware/blob/another-implementation/src/index.js#L57

By returning a value, you're resolving the promise with that value. As an example:

```
var P = require('bluebird');
P.reject(new Error('test'))
  .then(null, function(error){ return "something"})
  .catch(console.log.bind(console));
> (nothing logged)
```

Even though the original promise was rejected, then promise which the `.then` returns is resolved with the return value of the handler.

Whereas:
```
> P.reject(new Error('test'))
  .then(null, function(e){ throw e })
  .catch(console.log.bind(console))
> [Error: test]
```

**Comment by tomatau** [comment]
OK, so I'm retuning the result from the second dispatch call, however the lines of code you highlight are for a different promise to that which is returned.

The promise created [here](https://github.com/pburtchaell/redux-promise-middleware/issues/67#issuecomment-211599169) is a different promise to that which is returned from the middleware [here](https://github.com/tomatau/redux-promise-middleware/blob/another-implementation/src/index.js#L67).

So you would still be able to have a middleware stack that places your 'logger' before the promise and from within the logger:

```js
next(/* promise middleware */).catch(logRejection)
```

**Comment by Willyham** [comment]
Ahhh OK, now I understand. Sorry, I didn't really grasp this at first because that's generally considered an anti-pattern in its self, but I understand why you're doing it in this case. FWIW, the 'return' in then `onFulfill`, `onReject` functions are a bit of a red-herring. I would remove them and note that you're explicitly 'swallowing' that promise.

**Comment by tomatau** [comment]
Fair call, I agree that it's not clear and also pointless to return that dispatch within the promise (it was an artefact from previous implementations).

I've updated to remove the returns.

Although, I must admit, I'm not happy that these dispatch calls get lost inside the middleware, feels like they should be available to the consumer too.

Also, I don't agree that this is an anti-pattern at all. Anything can be a "bad-practice" in a particular situation. Why would this be an anti-pattern?... To propagate the original promise whilst responding to it's events in a non-disruptive manner seems to me like a good pattern...

**Comment by Willyham** [comment]
I agree that not every instance of a particular pattern is an anti-pattern (that's why I said generally considered). I think it's just important to recognise what the implications of a pattern are (and the impetus for something being called an anti-pattern).

The reason that not returning the promise from `.then` is generally considered an anti-pattern is because it means that any error raised in the code from `.then` will not get caught, even though the consumer might supply a `catch` block and expect that to happen. Kind of the same reason why you sense the code smell from not returning the dispatch call. 

In this case, it might make sense to use that pattern explicitly. If we don't return the promise from `.then` which we `catch`, we're explicitly saying 'you don't need to worry about rejections'. That usually doesn't make sense, but seeing as the rejection state is handled in the `_REJECTED` redux action, it's not a bad idea.

For what it's worth, right now, rejections are propagated back to the user, so even though the `_REJECTED` action is submitted to the store, there's an uncaught error unless the user adds a catch (which was slightly unexpected).

Given the above, I think the best shot at the most usable, intuitive and flexible interface would be (adapted from your code):

```
      return promise.then(
        (resolved = {}) => {
          const partialFulfilledAction = getResolvedPartialAction()
          return dispatch(
            isThunk(resolved)
              // bind the partial action to the thunk and dispatch it
              ? resolved.bind(null, partialFulfilledAction)
              // merge the partial action with the resolved payload if it exists
              : { ...partialFulfilledAction, ...!!resolved && { payload: resolved } }
          )
        },
        (rejected = {}) => {
          const partialRejectAction = getResolvedPartialAction(true)
          return dispatch(
            isThunk(rejected)
              // bind the partial action to the thunk and dispatch it
              ? rejected.bind(null, partialRejectAction)
              // merge the partial action with the resolved payload if it exists
              : { ...partialRejectAction, ...!!rejected && { payload: rejected } }
          )
        },
      )
```

We're returning the orignal promise type, returning the action to the user as the result of the dispatch call, and we're handling rejections and propagating them back to the user. The single caveat that this approach has is that the user shouldn't expect to handle the rejection with a `.catch`, but seeing as most people will only use `_REJECTED` to change the state, I think it's a minor detail.

**Comment by tomatau** [comment]
Hi @Willyham -- this is actually the implementation that I put forward for v2 (for the same reasons you're suggesting) but we moved away from it as many consumers were requesting access to the original promise.  Right now I'm already aware that my implementation linked above will propagate the uncaught promise, but this is acceptable as the _REJECTED action is still dispatched.

If you `npm i redux-promise-middleware@2` you will pretty much get the API you've just suggested.

**Comment by Willyham** [comment]
I see :(. Thanks for your patience as I pick through the history of this. We've sort of come on a long journey and ended up right back at the original request now. If we're deciding on the current _behaviour_ as of v3, then we can keep that as well as returning a promise of the same type with this change:

```
      return promise.then(
        (value = null) => {
          const resolvedAction = getAction(value, false);
          dispatch(resolvedAction);
          return { value, action: resolvedAction };
        },
        (reason = null) => {
          const rejectedAction = getAction(reason, true);
          dispatch(rejectedAction);
          const rejectedDetails = { reason, action: rejectedAction };
          throw rejectedDetails;
        });
```

All that's different is that we return `promise.then`, we return the value inside instead of calling `resolve` and we `throw` instead of calling `reject`. These two things are functionally equivalent, but this one retains the promise type (and I also think is more elegant). :dancers:

**Comment by tomatau** [comment]
I would still prefer to see the possibility of resolving a thunk for better composition -- modifying the meta data of a response action (to be different to the pending) is a big use-case for me. So, this tends towards returning the dispatch inside the promise as it's a standard redux pattern inside middleware `return next(action)`, but then there's the problem of rejected errors being swallowed.

So, I think returning the original promise actually removes the need for complex logic, having uncaught errors from the dispatch isn't so bad?

**Comment by Willyham** [comment]
That last point actually opens up a nice use case for my proposed change. Bluebird emits global `unhandledrejection` events on window for rejected promises (something supported in Chrome 49 for native promises but as far as I can see, not in other browsers). With the current implementation I wouldn't be able to make use of that event, but if we return the original promise it would work as expected.

**Comment by pburtchaell** [comment]
Sorry for my lack of participation in this discussion; I’ve been quite busy. I’ll try to read through everything soon.

**Comment by pburtchaell** [comment]
@Willyham I opened PR #82, which returns the original promise. Let me know if this resolves your issue.
