### ISSUE TITLE
Extra properties from action are being stripped off

### ISSUE THREAD

**Issue by ericmasiello** [pburtchaell/redux-promise-middleware#73]
This is more just a question / observation. 

I have a action creator that produces returns an action that looks like the following:

```
return {
        type: 'LOAD_WEATHER',
        payload,
        builder: 'weatherBuilderProvider'
      }
```
In my case, payload is a promise. I'm noticing that when the `LOAD_WEATHER_FULFILLED` action is sent my custom middleware, at that point, the `builder` property on my action has been stripped off. The only thing I see is the `type: 'LOAD_WEATHER_FULFILLED` and the payload with the resolved data. Is this by design? Or am I missing something? 

Is there any way to pass other meta data around in actions? Ideally I'd like `builder: 'weatherBuilderProvider'` to be preserved such that my other custom middleware can inspect that property and use its value to know how to transform the resolved data.

**Comment by pburtchaell** [comment]
Yeah, this is by design. The middleware is designed for Flux Standard Actions, aka FSA (see the docs for a link or just search GitHub). If you have extra properties like `builder` those should be in the `payload` or the `meta` properties.
