### ISSUE TITLE
Cancelable promises

### ISSUE THREAD

**Issue by pburtchaell** [pburtchaell/redux-promise-middleware#77]
[Cancelable Promises](https://docs.google.com/presentation/d/1V4vmC54gJkwAss1nfEt9ywc-QOVOfleRxD5qtpMpc8U/edit) have advanced to stage 1 at TC39. I'm creating this issue as a reminder that the middleware will need to be upgraded in the future to support this (if it becomes a part of the spec).  

I imagine the middleware will simply dispatch a third action type, e.g., `FOO_ACTION_CANCELLED`.

Reminder: stage 1 is a feature "worth working on" so cancelable promises are speculative.

**Comment by tomatau** [comment]
Yeh the CANCELLED action type sounds perfect

**Comment by steida** [comment]
No, it's terribly idea.Cancelling is another kind of rejection. Such change would introduce the whole universe of brittleness.

**Comment by pburtchaell** [comment]
> No, it's a terrible idea. Cancelling is another kind of rejection. 

From the proposal: "canceled is a third state, alongside fulfilled and rejected."

**Comment by steida** [comment]
And that's exactly what is wrong. It's completely against the promises principle. Hey, imagine you gave a promise to somehow. It can be resolved or rejected. Canceling is a lie in the contract.

**Comment by pburtchaell** [comment]
Well, @steida I didn't write the proposal. If the proposal changes, we won't add cancelable promises to the middleware. You aren't providing constructive feedback to this issue, but wasting my time.

**Comment by tomatau** [comment]
One of the major problems with promises is that they can't be cancelled. This is why many people have turned to observables.

Cancelling is a state that is decided by the consumer of the promise, not by the promise itself (such as rejected). This is a great way to avoid things like DOM updates as a result of the promise when the necessary nodes were unmounted between the promise being started and being resolved.

Cancelling is good and does not introduce brittleness.

The only concern I can think of is when there are multiple consumers of a promise. But if they all handle the cancelled state appropriately, then it should be fine.

**Comment by pburtchaell** [comment]
This proposal has been withdrawn. Closing the issue.
