### ISSUE TITLE
Integrate with redux-actions

### ISSUE THREAD

**Issue by lexfernandez** [pburtchaell/redux-promise-middleware#78]
i was trying to figure out how integrate redux-promise-middleware with redux-actions,
 is this posible or it is not necessary to use both components?

**Comment by tomatau** [comment]
All you would need to do is to return a promise from the payload creator and make sure that you have redux-promise-middleware. It would integrate quite nicely now thinking about it!

```js
// create a promise action
const saveThing = createAction('SAVE_THING', async (thing) => {
  const { data } = await saveThatThing(thing)
  return data
});
```

// use it
saveThing('123')
// should now dispatch `SAVE_THING_PENDING` and hopefully `SAVE_THING_FULFILLED`

**Comment by lexfernandez** [comment]
Thanks @tomatau ,

I will try to implement this on my project. I will let you know how it is going.

**Comment by pburtchaell** [comment]
@tomatau Would you mind adding a guide for this in the documentation? If you don't have time, I can at some point.

**Comment by pburtchaell** [comment]
Actually, never mind, [I added it just now](https://github.com/pburtchaell/redux-promise-middleware/blob/master/docs/guides/redux-actions.md), @tomatau. I'm going to close this issue, @lexfernandez, let us know if you need any further help.
