### ISSUE TITLE
Supplying another action as type

### ISSUE THREAD

**Issue by Pendla** [pburtchaell/redux-promise-middleware#8]
So, I have a scenario where I want to redirect on a success callback. This can currently be done by firing of an action like so: dispatch(transitionTo('/route')) with the help of redux-react-router. I was thinking though that it would be convenient to be able to fire of actions/methods in response to a fulfilled/rejected promise in general.

Something along these lines:
```javascript
export function login (email, password) {
  return {
    types: [LOGIN, loginSuccess(), LOGIN_ERROR],
    payload: {
      promise: authenticate(email, password)
    }
  };
}
```

The only problem I see with this, is that there would be no way of guaranteeing FSA compliancy by the subsequent actions fired manually by the developer.

Whats the general thought about this?

**Comment by pburtchaell** [comment]
I have a callback middleware I use in my current app for this. I pass in the callbacks through the action creator, but you don't need to do this.

```js
// actionCreator.js
export function login (email, password, loginSuccess) {
  return {
    types: [LOGIN, LOGIN_SUCCESS, LOGIN_ERROR],
    payload: {
      promise: authenticate(email, password),
      onSuccess: loginSuccess
    }
  };
}
```

```js
// callbackMiddleware.js
export default function callbackMiddleware() {
  return next => action => {
    if (!action.payload ||
        !action.payload.onSuccess ||
        !action.payload.onError) {
      return next(action);
    }

    const { promise, onSuccess, onError } = action.payload;

    return promise.then(
      (response) => onSuccess(response),
      (error) => onError(error)
    );
  };
}
```

**Comment by Pendla** [comment]
Alright, that is another good approach. It's a lot cleaner than my suggestion IMO. I presume this is something you omitted from redux-promise-middleware for a reason?

**Comment by pburtchaell** [comment]
Yeah, I think it is better off as its own middleware installed/used separately. I have https://github.com/pburtchaell/redux-callback-middleware and may put it there eventually, but the middleware seemed kinda simple to open source.
