### ISSUE TITLE
_network2.default.get is not a function

### ISSUE THREAD

**Issue by demiro** [pburtchaell/redux-promise-middleware#83]
I was following the complex example.... this is my actions file

`import * as types from '../../constants/actionsConstants';
import network from '../../utils/network';

export const getAll = () => ({
	type: types.TRAINEES_FETCH,
	payload: network.get({
		resource: 'player'
	})
});`

when I cakk getAll I get an error
_network2.default.get is not a function

I am using react native 0.26.2
react: 15.0.2
react-native: 0.26.2
redux 3.5.2
react-redux: 4.4.5
redux-promise-middleware: 3.0.0,

**Comment by pburtchaell** [comment]
1. What does `../../utils/network` look like? 
2. Do you have a Fetch API polyfill included?

**Comment by demiro** [comment]
(1.) Apart for the parameter changes it looks the same as does the one in the example... 

```
	import request from './request';

	/**
	 * @function Network
	 * @description Factory function to create a object that can send
	 * requests to a specific resource on the server.
	 * @param {string} resource The resource used for config
	 */
	const Network = resource => {
		let buildURL = ({ id, resource } = {}) => {
			let parameters = [
				'http://192.168.0.7:1337/'
			];

			if (resource) parameters.concat([resource]);
			if (id) parameters.concat([id]);
```

the .request is exactly the same


(2.) I don't know if it comes bundled with RN, but fetch works perfectly fine for me. But I did install it just now to be sure, the error is still the same.... 

(3.) when I run the project without remoteConsole on, the error shows slightly different

![screenshot_20160602-023243](https://cloud.githubusercontent.com/assets/514682/15731162/e695384e-286a-11e6-8475-9a05f7df7a9c.png)



I wonder why it reffers to _network2.default get though


(4.) If I do it like this in my actions... it works

```
import * as types from '../../constants/actionsConstants';



function request(url, options) {
	return new Promise((resolve, reject) => {
		if (!url) reject(new Error('URL parameter required'));
		if (!options) reject(new Error('Options parameter required'));

		fetch(url, options)
			.then(response => response.json())
			.then(response => {
				if (response.errors) reject(response.errors);
				else resolve(response);
			})
			.catch(reject);
	});
}


export const getAll = () => ({
	type: types.TRAINEES_FETCH,
	payload: request('http://192.168.0.7:1337/player', {method: 'GET'})
});
```

**Comment by pburtchaell** [comment]
The `Network` function is a factory function so it returns an object. I expect the object isn't being returned properly. 

1. Did you construct the object, e.g., fire the function?
2. Is the constructed object exported?

Try `typeof network` in your action creator. It should return `"object"` and not `"function"`.

**Comment by demiro** [comment]
I don't know, I just used it as in example... for now, I completely skip it and use ./request directly, works completely fine. thanks for the help
