### ISSUE TITLE
Feature Request: Retain non-essential keys on action object

### ISSUE THREAD

**Issue by calekennedy** [pburtchaell/redux-promise-middleware#92]
Lets say that I produce an action 

```
const formSubmitted = (request, unique_identifier) => ({
  type: FORM_SUBMITTED,
  unique_identifier,
  payload: request
});
```

when this action reaches my reducer, after passing through the middleware, several different things happen. 

1. type is now appended with a status.
2. unique_identifier has been stripped from the action
3. payload is a resolved promise

Basically, I have the following...

```
action.type === 'FORM_SUBMITTED_[STATUS]'
action.payload === Object //whatever you'd expect
action.unique_identifier === undefined
```

This creates an issue due to the structure of my application. The unique_identifier is used by the reducer to determine if it should attempt to handle the action or simply stand down. The redux application is made up of smaller components that can be reused, and as such, certain reducers are reused. This is actually a really good pattern in my use case, but it seems to be atypical.

The easiest way for me to solve this problem is to retain the unique_identifier key after the payload is received in the reducer. I don't understand why it is necessary to strip it. 

The current hack involves making the reducer capable of deciphering something like the following...

```
action.type --> 'FORM_SUBMITTED_[unique_identifier]_[STATUS]'
```

As you can tell, that's a major hack and I would prefer to avoid it.

Is there a particular reason the non-essential keys are stripped? 

Is there any chance of being able to preserve them?

**Comment by calekennedy** [comment]
I looked through the source and noticed that you're performing the following de-structuring.
```
// Deconstruct the properties of the original action object to constants
      const { type, payload, meta } = action;
```
Then, something like the following may work to solve my issue...
```
      const getAction = (newPayload, isRejected, oldAction) => ({
        ...oldAction,
        type: `${type}_${isRejected ? REJECTED : FULFILLED}`,
        ...newPayload ? {
          payload: newPayload
        } : {},
        ...!!meta ? { meta } : {},
        ...isRejected ? {
          error: true
        } : {}
      });
```

Another solution might be for me to move my property into the meta object.

**Comment by pburtchaell** [comment]
> My temporary solution will be moving my property into meta, since you are preserving that.

Is there a reason why this wouldn't be the permanent solution?

> unique_identifier has been stripped from the action. [...] I don't understand why it is necessary to strip it.

This is intentional; the middleware follows [the Flux Standard Action](https://github.com/acdlite/flux-standard-action) spec.

**Comment by pburtchaell** [comment]
I'm closing this issue as invalid. Please reopen if you would like to further discuss.
