### ISSUE TITLE
If rejection reason is instance of `Error` it's stack trace get lost

### ISSUE THREAD

**Issue by umidbekkarimov** [pburtchaell/redux-promise-middleware#93]
When I got some `syntax` errors or any other - middleware overrides it with it's own error and it's stack trace get lost

![screen shot 2016-07-05 at 11 33 12](https://cloud.githubusercontent.com/assets/4734297/16577115/591cef3a-42a4-11e6-8964-4587d04cad17.png)

**Comment by pburtchaell** [comment]
Resolved and released as `redux-promise-middleware@3.3.1`.

**Comment by mrtnbroder** [comment]
This actually broke my whole app. Errors, not being thrown as an instance of Error now get reject with the false reason. This should be handled by the user and not by this lib. I'm voting for a rollback.

**Comment by pburtchaell** [comment]
Yep, are rolling back in the next release @mrtnbroder. There is a PR open at #101.
