### ISSUE TITLE
Change of export of promiseMiddleware function to non default.

### ISSUE THREAD

**Issue by rluiten** [pburtchaell/redux-promise-middleware#95]
This is not a bug but a query
I notice you changed the export the function from the module.
Is there some reason to move away from the export default ? back to directly on exports ?

Change to exports instead of default export in v3.3.2

I am working in typescript, I created a minimal type definition to use redux-promise-middleware and it was exported with `export default` in 3.3.0 and worked fine.

I happened to update to 3.3.2 this morning and it caused errors, this happened because my typescript definition still said default export so dumbly pulls in the wrong thing and runs with no compile errors because my type definition is lying.

Just thought I would mention it, changing isn't a big deal, but mentioning the change in comments would be very useful to me.

**Comment by pburtchaell** [comment]
> Is there some reason to move away from the export default ? back to directly on exports ?

I've added [release notes for version 3.3.2](https://github.com/pburtchaell/redux-promise-middleware/releases/tag/3.3.2). This should clarify any questions you have.

I apologize for not posting the release notes easier. I published the release while at work and didn't have time to post these notes as well.

I'm going to close this issue. Please let me know if you have any other comments. 😄

**Comment by rluiten** [comment]
Thanks for the clarification

**Comment by gregj1** [comment]
@rluiten, would you mind posting the working type definition? I'm working with the DefinitatelyTyped version dated 2016-01-08T03:25:28.000Z (below). I'm getting an error at runtime, but I'm not experienced enough with TypeScript to fix it myself.

```
// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/e7df72296ea2a55f57ece35e28bb930ae93b19b5/redux-promise-middleware/redux-promise-middleware.d.ts
declare module "redux-promise-middleware" {
    function promiseMiddleware(config?: { promiseTypeSuffixes: string[] }): Redux.Middleware;

    export default promiseMiddleware;
}
```

**Comment by rluiten** [comment]
This is whats working for me now.
```typescript
declare module "redux-promise-middleware" {
    import { Dispatch } from 'redux';
    function createMiddleware(): Dispatch<any>;
    export = createMiddleware;
}
```
The change that matters is the export = line
So just change `export default promiseMiddleware;` to `export = createMiddleware;` in yours
