### ISSUE TITLE
Validate `action.type`

### ISSUE THREAD

**Issue by umidbekkarimov** [pburtchaell/redux-promise-middleware#96]
If you pass
```javascript
dispatch({
    payload: Promise.resolve(true)
});
```

It will produce `undefined_PENDING`, `undefined_FULFILLED` and `undefined_REJECTED` action types

Something same would be for all non string action types

**Comment by pburtchaell** [comment]
I should be understood a type is required [based off the examples in the introduction](https://github.com/pburtchaell/redux-promise-middleware/blob/master/docs/introduction.md). Furthermore, [the Redux documentation](http://redux.js.org/docs/basics/Actions.html) states `type` is required: 

> Actions are plain JavaScript objects. Actions must have a type property that indicates the type of action being performed. Types should typically be defined as string constants. Once your app is large enough, you may want to move them into a separate module.

**Comment by umidbekkarimov** [comment]
@pburtchaell 

> type is required

Yep, but during development many things can go wrong.

For example:
```javascript
import {
     SOME_LOGN_ACTION_NAME
} from './action-types';

dispatch({
    type: SOME_LOGN_ACTION_NAME,
    payload: doSomething() 
});
```

Here I should get `undefined` error from redux - because I mistyped action type variable name, but instead of it `middleware` executes action with new `undefined_PENDING` and `undefined_FULFILLED` actions, and give me headaches.

**Comment by pburtchaell** [comment]
> Yep, but during development many things can go wrong.

Yes, but it isn't the responsibility of this middleware to do type checking. Instead, I would suggest moving this into a separate middleware.

**Comment by umidbekkarimov** [comment]
> Yes, but it isn't the responsibility of this middleware to do type checking 

Yes, but at least it should give a chance for `redux` to validate it.

P.S. Will you give me another "Yes, but" argument ? 😅 I don't want to give up.

@gaearon need your help here, what do you think about this situation?

**Comment by tomatau** [comment]
Write tests for your dispatch calls -- they should be checking the type is what you expect.
